# Generated by Django 5.1.1 on 2024-10-18 19:07

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobstartedreceipt",
            name="time_accepted",
        ),
        migrations.AddField(
            model_name="jobfinishedreceipt",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 1, 1, 0, 0, tzinfo=datetime.UTC)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobstartedreceipt",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2020, 1, 1, 0, 0, tzinfo=datetime.UTC)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobstartedreceipt",
            name="ttl",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="JobAcceptedReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("job_uuid", models.UUIDField()),
                ("validator_hotkey", models.CharField(max_length=256)),
                ("miner_hotkey", models.CharField(max_length=256)),
                ("validator_signature", models.CharField(max_length=256)),
                ("miner_signature", models.CharField(blank=True, max_length=256, null=True)),
                ("timestamp", models.DateTimeField()),
                ("time_accepted", models.DateTimeField()),
                ("ttl", models.IntegerField()),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job_uuid",), name="receipts_unique_jobacceptedreceipt_job_uuid"
                    )
                ],
            },
        ),
    ]
