# Generated by Django 4.2.23 on 2025-08-26 08:41

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_remove_jobstartedreceipt_max_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfinishedreceipt',
            name='block_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=list, help_text='List of block numbers used to pay for this job', size=None),
        ),
        migrations.AddIndex(
            model_name='jobfinishedreceipt',
            index=django.contrib.postgres.indexes.GinIndex(fields=['block_numbers'], name='jobfinished_blocknums_gin'),
        ),
    ]
