# Generated by Django 4.2.16 on 2025-01-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0004_remove_jobstartedreceipt_max_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobfinishedreceipt",
            name="block_numbers",
            field=models.JSONField(
                default=list, help_text="List of block numbers used to pay for this job"
            ),
        ),
    ]
