# Generated by Django 4.2.23 on 2025-08-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0004_remove_jobstartedreceipt_max_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobfinishedreceipt",
            name="block_numbers",
            field=models.JSONField(
                default=list,
                help_text="List of block numbers used to pay for this job",
            ),
        ),
    ]
