# Generated by Django 4.2.9 on 2024-01-29 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="syntheticjob",
            name="score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="syntheticjobbatch",
            name="scored",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="syntheticjob",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="synthetic_jobs",
                to="validator.syntheticjobbatch",
            ),
        ),
    ]
