# Generated by Django 4.2.9 on 2024-02-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0002_syntheticjob_score_syntheticjobbatch_scored_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="syntheticjob",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="syntheticjob",
            constraint=models.UniqueConstraint(fields=("batch", "miner"), name="one_job_per_batch_per_miner"),
        ),
    ]
