# Generated by Django 4.2.9 on 2024-02-03 10:55

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0003_alter_syntheticjob_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganicJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("miner_address", models.CharField(max_length=255)),
                ("miner_address_ip_version", models.IntegerField()),
                ("miner_port", models.IntegerField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "miner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="validator.miner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
