# Generated by Django 4.2.9 on 2024-02-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0004_organicjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicjob",
            name="job_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="syntheticjob",
            name="job_description",
            field=models.TextField(blank=True),
        ),
    ]
