# Generated by Django 4.2.11 on 2024-05-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0005_organicjob_job_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyntheticJobContents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("weights_version", models.IntegerField(db_index=True)),
                ("answer", models.TextField()),
                ("contents", models.BinaryField()),
            ],
        ),
    ]
