# Generated by Django 4.2.11 on 2024-05-15 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0005_organicjob_job_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinerBlacklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "miner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="validator.miner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blacklisted Miner",
                "verbose_name_plural": "Blacklisted Miners",
            },
        ),
    ]
