# Generated by Django 4.2.11 on 2024-05-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0006_syntheticjobcontents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syntheticjobcontents",
            name="contents",
            field=models.TextField(),
        ),
    ]
