# Generated by Django 4.2.11 on 2024-05-16 11:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0006_minerblacklist"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminJobRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "timeout",
                    models.PositiveIntegerField(default=0, help_text="timeout in seconds"),
                ),
                (
                    "docker_image",
                    models.CharField(help_text="docker image for job execution", max_length=255),
                ),
                (
                    "raw_script",
                    models.TextField(blank=True, help_text="raw script to be executed"),
                ),
                (
                    "args",
                    models.TextField(
                        blank=True,
                        help_text="arguments passed to the script or docker image",
                    ),
                ),
                (
                    "env",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="environment variables for the job",
                    ),
                ),
                (
                    "use_gpu",
                    models.BooleanField(default=False, help_text="Whether to use GPU for the job"),
                ),
                (
                    "input_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the input data source",
                        max_length=1000,
                    ),
                ),
                (
                    "output_url",
                    models.TextField(blank=True, help_text="URL for uploading output"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "miner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="validator.miner",
                    ),
                ),
            ],
        ),
    ]
