# Generated by Django 4.2.11 on 2024-05-21 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0008_rename_job_uuid_adminjobrequest_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="syntheticjob",
            name="one_job_per_batch_per_miner",
        ),
    ]
