# Generated by Django 4.2.11 on 2024-06-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0010_jobreceipt_jobreceipt_unique_job_receipt_job_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicjob",
            name="stderr",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="organicjob",
            name="stdout",
            field=models.TextField(blank=True, default=""),
        ),
    ]
