# Generated by Django 4.2.13 on 2024-06-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0015_alter_systemevent_subtype_alter_systemevent_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicjob",
            name="executor_class",
            field=models.CharField(default="spin_up-4min.gpu-24gb", max_length=255),
        ),
        migrations.AddField(
            model_name="syntheticjob",
            name="executor_class",
            field=models.CharField(default="spin_up-4min.gpu-24gb", max_length=255),
        ),
    ]
