# Generated by Django 4.2.13 on 2024-06-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0016_organicjob_executor_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminjobrequest",
            name="executor_class",
            field=models.CharField(
                default="spin_up-4min.gpu-24gb", help_text="executor hardware class", max_length=255
            ),
        ),
    ]
