# Generated by Django 4.2.13 on 2024-07-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0019_minermanifest_minermanifest_unique_miner_manifest"),
    ]

    operations = [
        migrations.AddField(
            model_name="minermanifest",
            name="online_executor_count",
            field=models.IntegerField(default=0),
        ),
    ]
