# Generated by Django 4.2.13 on 2024-07-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0021_alter_systemevent_subtype"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobStartedReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_uuid", models.UUIDField()),
                ("miner_hotkey", models.CharField(max_length=256)),
                ("validator_hotkey", models.CharField(max_length=256)),
                ("time_accepted", models.DateTimeField()),
                ("max_timeout", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="jobreceipt",
            name="unique_job_receipt_job_uuid",
        ),
        migrations.AddConstraint(
            model_name="jobreceipt",
            constraint=models.UniqueConstraint(
                fields=("job_uuid",), name="unique_jobreceipt_job_uuid"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobstartedreceipt",
            constraint=models.UniqueConstraint(
                fields=("job_uuid",), name="unique_jobstartedreceipt_job_uuid"
            ),
        ),
    ]
