# Generated by Django 4.2.13 on 2024-07-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0022_jobstartedreceipt_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="JobReceipt",
            new_name="JobFinishedReceipt",
        ),
        migrations.RemoveConstraint(
            model_name="jobfinishedreceipt",
            name="unique_jobreceipt_job_uuid",
        ),
        migrations.AddConstraint(
            model_name="jobfinishedreceipt",
            constraint=models.UniqueConstraint(
                fields=("job_uuid",), name="unique_jobfinishedreceipt_job_uuid"
            ),
        ),
    ]
