# Generated by Django 4.2.13 on 2024-07-30 21:03

import compute_horde_validator.validator.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0026_alter_systemevent_subtype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
                (
                    "weights",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
                (
                    "salt",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        default=compute_horde_validator.validator.models.get_random_salt,
                        size=None,
                    ),
                ),
                ("version_key", models.IntegerField()),
                ("block", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revealed_at", models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="weights",
            constraint=models.UniqueConstraint(fields=("block",), name="unique_block"),
        ),
    ]
