# Generated by Django 4.2.13 on 2024-08-12 12:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("validator", "0028_alter_systemevent_subtype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Epoch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.BigIntegerField()),
                ("stop", models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="syntheticjobbatch",
            name="block",
            field=models.BigIntegerField(
                help_text="Block number for which this batch is scheduled",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="syntheticjobbatch",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="syntheticjobbatch",
            name="accepting_results_until",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="syntheticjobbatch",
            name="started_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddConstraint(
            model_name="epoch",
            constraint=models.UniqueConstraint(
                fields=("start", "stop"), name="unique_epoch"
            ),
        ),
        migrations.AddField(
            model_name="syntheticjobbatch",
            name="epoch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="validator.epoch",
            ),
        ),
    ]
