# Generated by Django 4.2.13 on 2024-08-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0030_alter_systemevent_subtype_alter_systemevent_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("WEIGHT_SETTING_SUCCESS", "Weight Setting Success"),
                    ("WEIGHT_SETTING_FAILURE", "Weight Setting Failure"),
                    ("MINER_ORGANIC_JOB_FAILURE", "Miner Organic Job Failure"),
                    ("MINER_ORGANIC_JOB_SUCCESS", "Miner Organic Job Success"),
                    ("MINER_SYNTHETIC_JOB_SUCCESS", "Miner Synthetic Job Success"),
                    ("MINER_SYNTHETIC_JOB_FAILURE", "Miner Synthetic Job Failure"),
                    ("RECEIPT_FAILURE", "Receipt Failure"),
                    ("FACILITATOR_CLIENT_ERROR", "Facilitator Client Error"),
                    ("VALIDATOR_MINERS_REFRESH", "Validator Miners Refresh"),
                    ("VALIDATOR_FAILURE", "Validator Failure"),
                    ("VALIDATOR_TELEMETRY", "Validator Telemetry"),
                    ("VALIDATOR_CHANNEL_LAYER_ERROR", "Validator Channel Layer Error"),
                ],
                max_length=255,
            ),
        ),
    ]
