# Generated by Django 4.2.15 on 2024-08-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0031_epoch_syntheticjobbatch_block_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Epoch",
            new_name="Cycle",
        ),
        migrations.RemoveConstraint(
            model_name="cycle",
            name="unique_epoch",
        ),
        migrations.RenameField(
            model_name="syntheticjobbatch",
            old_name="epoch",
            new_name="cycle",
        ),
        migrations.AddConstraint(
            model_name="cycle",
            constraint=models.UniqueConstraint(fields=("start", "stop"), name="unique_cycle"),
        ),
    ]
