# Generated by Django 4.2.15 on 2024-09-06 18:17

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0035_alter_systemevent_subtype"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("s3_url", models.URLField(max_length=1000)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("generator_version", models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="SolveWorkload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workload_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("seed", models.BigIntegerField()),
                ("s3_url", models.URLField(max_length=1000)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "finished_at",
                    models.DateTimeField(db_index=True, default=None, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromptSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="validator.promptseries",
                    ),
                ),
                (
                    "synthetic_job",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="validator.syntheticjob",
                    ),
                ),
                (
                    "workload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="validator.solveworkload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("answer", models.TextField(null=True)),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompts",
                        to="validator.promptsample",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="promptsample",
            constraint=models.UniqueConstraint(
                fields=("series", "workload"), name="unique_series_workload"
            ),
        ),
    ]
