# Generated by Django 4.2.15 on 2024-09-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0036_prompt_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promptseries",
            name="generator_version",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
