# Generated by Django 4.2.15 on 2024-09-12 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0037_alter_promptseries_generator_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="weights",
            name="cycle",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weights",
                to="validator.cycle",
            ),
        ),
    ]
