# Generated by Django 4.2.15 on 2024-09-19 19:59

from django.db import migrations, models


def populate_commit_block(apps, schema_editor):
    Weights = apps.get_model("validator", "Weights")
    Weights.objects.update(commit_block=models.F("block"))


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0037_alter_promptseries_generator_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="weights",
            name="commit_block",
            field=models.BigIntegerField(null=True),
        ),
        migrations.RunPython(populate_commit_block, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="weights",
            name="commit_block",
            field=models.BigIntegerField(),
        ),
    ]
