# Generated by Django 4.2.15 on 2024-10-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0038_alter_systemevent_subtype_alter_systemevent_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobFinishedReceipt',
        ),
        migrations.DeleteModel(
            name='JobStartedReceipt',
        ),
    ]
