# Generated by Django 4.2.15 on 2024-10-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0039_delete_jobfinishedreceipt_delete_jobstartedreceipt"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="minermanifest",
            name="unique_miner_manifest",
        ),
        migrations.AddField(
            model_name="minermanifest",
            name="executor_class",
            field=models.CharField(default="spin_up-4min.gpu-24gb", max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="minermanifest",
            constraint=models.UniqueConstraint(
                fields=("miner", "batch", "executor_class"), name="unique_miner_manifest"
            ),
        ),
    ]
