# Generated by Django 4.2.15 on 2024-10-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0040_remove_minermanifest_unique_miner_manifest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidatorWhitelist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hotkey", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
