# Generated by Django 4.2.16 on 2025-01-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0044_alter_systemevent_subtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemevent",
            name="data",
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
