# Generated by Django 4.2.16 on 2025-01-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0044_alter_systemevent_subtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicjob",
            name="block",
            field=models.BigIntegerField(
                help_text="Block number on which this job is scheduled", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="organicjob",
            index=models.Index(fields=["block"], name="validator_o_block_50c152_idx"),
        ),
    ]
