# Generated by Django 4.2.16 on 2025-02-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0046_alter_organicjob_status_alter_syntheticjob_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="syntheticjobbatch",
            name="should_be_scored",
            field=models.BooleanField(default=True),
        ),
    ]
