# Generated by Django 4.2.16 on 2025-02-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0046_alter_organicjob_status_alter_syntheticjob_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minermanifest",
            name="executor_count",
            field=models.IntegerField(
                default=0,
                help_text="The total number of available executors of this class as reported by the miner",
            ),
        ),
        migrations.AlterField(
            model_name="minermanifest",
            name="online_executor_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of executors that finished or properly declined a job request during the batch",
            ),
        ),
    ]
