# Generated by Django 4.2.16 on 2025-02-05 12:24

from django.db import IntegrityError, migrations


def populate_null_blocks_and_cycles(apps, schema_editor):
    Cycle = apps.get_model("validator", "Cycle")
    SyntheticJobBatch = apps.get_model("validator", "SyntheticJobBatch")

    dummy_cycle, _ = Cycle.objects.get_or_create(start=0, stop=2)
    SyntheticJobBatch.objects.filter(cycle__isnull=True).update(cycle=dummy_cycle)

    i = -1
    for batch in SyntheticJobBatch.objects.filter(block__isnull=True):
        while True:
            try:
                batch.block = i
                batch.save()
            except IntegrityError:
                i -= 1
            else:
                i -= 1
                break


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("validator", "0047_syntheticjobbatch_should_be_scored"),
    ]

    operations = [
        migrations.RunPython(populate_null_blocks_and_cycles, migrations.RunPython.noop),
    ]
