# Generated by Django 4.2.16 on 2025-02-05 16:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0047_alter_minermanifest_executor_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="minerblacklist",
            name="blacklisted_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="minerblacklist",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="minerblacklist",
            name="reason",
            field=models.TextField(
                choices=[("MANUAL", "Manual"), ("JOB_FAILED", "Job Failed")], default="MANUAL"
            ),
        ),
        migrations.AddField(
            model_name="minerblacklist",
            name="reason_details",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="minerblacklist",
            name="miner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="validator.miner"
            ),
        ),
    ]
