# Generated by Django 4.2.16 on 2025-02-05 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0048_populate_null_block_cycle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syntheticjobbatch",
            name="block",
            field=models.BigIntegerField(
                help_text="Block number for which this batch is scheduled", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="syntheticjobbatch",
            name="cycle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="validator.cycle",
            ),
        ),
    ]
