# Generated by Django 4.2.16 on 2025-02-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0049_alter_syntheticjobbatch_block_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicjob",
            name="artifacts",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
