# Generated by Django 4.2.16 on 2025-02-07 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0048_minerblacklist_blacklisted_at_and_more'),
        ('validator', '0049_alter_syntheticjobbatch_block_and_more'),
    ]

    operations = [
    ]
