# Generated by Django 4.2.16 on 2025-02-17 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0050_alter_systemevent_subtype_alter_systemevent_type"),
        ("validator", "0050_minerblacklist_blacklisted_at_and_more"),
    ]

    operations = []
