# Generated by Django 4.2.16 on 2025-02-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0051_merge_20250217_1128"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicjob",
            name="artifacts",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
