# Generated by Django 4.2.16 on 2025-02-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0052_minerblacklist_blacklisted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicjob",
            name="on_trusted_miner",
            field=models.BooleanField(default=False),
        ),
    ]
