# Generated by Django 4.2.19 on 2025-02-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0053_organicjob_cheated_alter_minerblacklist_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicjob",
            name="on_trusted_miner",
            field=models.BooleanField(default=False),
        ),
    ]
