# Generated by Django 4.2.19 on 2025-02-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0054_organicjob_error_detail_organicjob_error_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicjob",
            name="on_trusted_miner",
            field=models.BooleanField(default=False),
        ),
    ]
