# Generated by Django 4.2.19 on 2025-03-06 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0055_organicjob_on_trusted_miner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminjobrequest",
            name="raw_script",
        ),
    ]
