# Generated by Django 4.2.19 on 2025-03-04 13:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0055_organicjob_on_trusted_miner"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetagraphSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("block", models.BigIntegerField(unique=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alpha_stake",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=None
                    ),
                ),
                (
                    "tao_stake",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=None
                    ),
                ),
                (
                    "stake",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=None
                    ),
                ),
                (
                    "uids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
                (
                    "hotkeys",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), size=None
                    ),
                ),
                (
                    "serving_hotkeys",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), size=None
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="miner",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="miner",
            name="ip_version",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="miner",
            name="port",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="miner",
            name="uid",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="systemevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("WEIGHT_SETTING_SUCCESS", "Weight Setting Success"),
                    ("WEIGHT_SETTING_FAILURE", "Weight Setting Failure"),
                    ("MINER_ORGANIC_JOB_INFO", "Miner Organic Job Info"),
                    ("MINER_ORGANIC_JOB_FAILURE", "Miner Organic Job Failure"),
                    ("MINER_ORGANIC_JOB_SUCCESS", "Miner Organic Job Success"),
                    ("MINER_SYNTHETIC_JOB_SUCCESS", "Miner Synthetic Job Success"),
                    ("MINER_SYNTHETIC_JOB_FAILURE", "Miner Synthetic Job Failure"),
                    ("RECEIPT_FAILURE", "Receipt Failure"),
                    ("FACILITATOR_CLIENT_ERROR", "Facilitator Client Error"),
                    ("VALIDATOR_MINERS_REFRESH", "Validator Miners Refresh"),
                    ("VALIDATOR_SYNTHETIC_JOBS_FAILURE", "Validator Synthetic Jobs Failure"),
                    ("VALIDATOR_FAILURE", "Validator Failure"),
                    ("VALIDATOR_TELEMETRY", "Validator Telemetry"),
                    ("VALIDATOR_CHANNEL_LAYER_ERROR", "Validator Channel Layer Error"),
                    ("VALIDATOR_SYNTHETIC_JOB_SCHEDULED", "Validator Synthetic Job Scheduled"),
                    (
                        "VALIDATOR_OVERSLEPT_SCHEDULED_JOB_WARNING",
                        "Validator Overslept Scheduled Job Warning",
                    ),
                    ("LLM_PROMPT_GENERATION", "Llm Prompt Generation"),
                    ("LLM_PROMPT_ANSWERING", "Llm Prompt Answering"),
                    ("LLM_PROMPT_SAMPLING", "Llm Prompt Sampling"),
                    ("BURNING_INCENTIVE", "Burning Incentive"),
                    ("METAGRAPH_SYNCING", "Metagraph Syncing"),
                ],
                max_length=255,
            ),
        ),
    ]
