# Generated by Django 4.2.19 on 2025-03-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0056_metagraphsnapshot_miner_address_miner_ip_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metagraphsnapshot",
            name="block",
            field=models.BigIntegerField(),
        ),
    ]
