# Generated by Django 4.2.19 on 2025-03-06 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0056_minerpreliminaryreservation"),
        ("validator", "0057_alter_metagraphsnapshot_block"),
    ]

    operations = []
