# Generated by Django 4.2.20 on 2025-03-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0058_merge_20250306_1345"),
    ]

    operations = [
        migrations.AlterField(
            model_name="miner",
            name="address",
            field=models.CharField(default="0.0.0.0", max_length=255),
        ),
        migrations.AlterField(
            model_name="miner",
            name="ip_version",
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name="miner",
            name="port",
            field=models.IntegerField(default=0),
        ),
    ]
