# Generated by Django 4.2.19 on 2025-03-07 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0059_alter_miner_address_alter_miner_ip_version_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminjobrequest",
            name="raw_script",
        ),
    ]
