# Generated by Django 4.2.19 on 2025-04-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0060_remove_adminjobrequest_raw_script"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemevent",
            name="subtype",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                    ("SUBTENSOR_CONNECTIVITY_ERROR", "Subtensor Connectivity Error"),
                    ("COMMIT_WEIGHTS_SUCCESS", "Commit Weights Success"),
                    ("COMMIT_WEIGHTS_ERROR", "Commit Weights Error"),
                    ("COMMIT_WEIGHTS_UNREVEALED_ERROR", "Commit Weights Unrevealed Error"),
                    ("REVEAL_WEIGHTS_ERROR", "Reveal Weights Error"),
                    ("REVEAL_WEIGHTS_SUCCESS", "Reveal Weights Success"),
                    ("SET_WEIGHTS_SUCCESS", "Set Weights Success"),
                    ("SET_WEIGHTS_ERROR", "Set Weights Error"),
                    ("GENERIC_ERROR", "Generic Error"),
                    ("WRITING_TO_CHAIN_TIMEOUT", "Writing To Chain Timeout"),
                    ("WRITING_TO_CHAIN_GENERIC_ERROR", "Writing To Chain Generic Error"),
                    ("GIVING_UP", "Giving Up"),
                    ("MANIFEST_ERROR", "Manifest Error"),
                    ("MANIFEST_TIMEOUT", "Manifest Timeout"),
                    ("MINER_CONNECTION_ERROR", "Miner Connection Error"),
                    ("MINER_SEND_ERROR", "Miner Send Error"),
                    ("MINER_SCORING_ERROR", "Miner Scoring Error"),
                    ("JOB_NOT_STARTED", "Job Not Started"),
                    ("JOB_REJECTED", "Job Rejected"),
                    ("JOB_EXCUSED", "Job Excused"),
                    ("JOB_CHEATED", "Job Cheated"),
                    ("MINER_BLACKLISTED", "Miner Blacklisted"),
                    ("JOB_EXECUTION_TIMEOUT", "Job Execution Timeout"),
                    ("RECEIPT_FETCH_ERROR", "Receipt Fetch Error"),
                    ("RECEIPT_SEND_ERROR", "Receipt Send Error"),
                    ("SPECS_SENDING_ERROR", "Specs Send Error"),
                    ("HEARTBEAT_ERROR", "Heartbeat Error"),
                    ("UNEXPECTED_MESSAGE", "Unexpected Message"),
                    ("UNAUTHORIZED", "Unauthorized"),
                    ("SYNTHETIC_BATCH", "Synthetic Batch"),
                    ("SYNTHETIC_JOB", "Synthetic Job"),
                    ("CHECKPOINT", "Checkpoint"),
                    ("OVERSLEPT", "Overslept"),
                    ("WARNING", "Warning"),
                    ("FAILED_TO_WAIT", "Failed To Wait"),
                    ("TRUSTED_MINER_NOT_CONFIGURED", "Trusted Miner Not Configured"),
                    ("LLM_PROMPT_ANSWERS_MISSING", "Llm Prompt Answers Missing"),
                    ("INSUFFICIENT_PROMPTS", "Insufficient Prompts"),
                    ("UNPROCESSED_WORKLOADS", "Unprocessed Workloads"),
                    ("PROMPT_GENERATION_STARTED", "Prompt Generation Started"),
                    ("PROMPT_SAMPLING_SKIPPED", "Prompt Sampling Skipped"),
                    ("NEW_WORKLOADS_CREATED", "New Workloads Created"),
                    ("ERROR_UPLOADING_TO_S3", "Error Uploading To S3"),
                    ("ERROR_DOWNLOADING_FROM_S3", "Error Downloading From S3"),
                    ("ERROR_DOWNLOADING_FROM_HUGGINGFACE", "Error Downloading From Huggingface"),
                    ("ERROR_DURING_SECURITY_CHECK", "Error Failed Security Check"),
                    ("ERROR_EXECUTOR_REPORTED_TIMEOUT", "Error Executor Reported Timeout"),
                    ("ERROR_VALIDATOR_REPORTED_TIMEOUT", "Error Validator Reported Timeout"),
                    (
                        "LLM_PROMPT_ANSWERS_DOWNLOAD_WORKER_FAILED",
                        "Llm Prompt Answers Download Worker Failed",
                    ),
                    ("APPLIED_BURNING", "Applied Burning"),
                    ("NO_BURNING", "No Burning"),
                ],
                max_length=255,
            ),
        ),
    ]
