# Generated by Django 4.2.19 on 2025-03-31 20:35

import compute_horde_core.executor_class
import compute_horde_validator.validator.generation_profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0060_remove_adminjobrequest_raw_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptseries',
            name='generation_profile',
            field=models.CharField(choices=[(compute_horde_validator.validator.generation_profile.PromptGenerationProfile['default_a6000'], compute_horde_validator.validator.generation_profile.PromptGenerationProfile['default_a6000']), (compute_horde_validator.validator.generation_profile.PromptGenerationProfile['default_a100'], compute_horde_validator.validator.generation_profile.PromptGenerationProfile['default_a100'])], default=compute_horde_validator.validator.generation_profile.PromptGenerationProfile['default_a6000'], max_length=255),
        ),
        migrations.AddField(
            model_name='solveworkload',
            name='executor_class',
            field=models.CharField(choices=[(compute_horde_core.executor_class.ExecutorClass['spin_up_4min__gpu_24gb'], compute_horde_core.executor_class.ExecutorClass['spin_up_4min__gpu_24gb']), (compute_horde_core.executor_class.ExecutorClass['always_on__gpu_24gb'], compute_horde_core.executor_class.ExecutorClass['always_on__gpu_24gb']), (compute_horde_core.executor_class.ExecutorClass['always_on__llm__a6000'], compute_horde_core.executor_class.ExecutorClass['always_on__llm__a6000'])], default=compute_horde_core.executor_class.ExecutorClass['always_on__llm__a6000'], max_length=255),
        ),
    ]
