# Generated by Django 4.2.19 on 2025-05-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0061_miner_collateral_miner_evm_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicjob",
            name="slashed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="miner",
            name="evm_address",
            field=models.CharField(max_length=42, null=True),
        ),
    ]
