# Generated by Django 4.2.19 on 2025-05-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0061_organicjob_upload_results"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicjob",
            name="streaming_details",
            field=models.JSONField(default=None, null=True),
        ),
    ]
