# Generated by Django 4.2.21 on 2025-05-13 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0061_organicjob_upload_results"),
    ]

    operations = [
        migrations.AddField(
            model_name="cycle",
            name="set_compute_time_allowance",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="systemevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("WEIGHT_SETTING_SUCCESS", "Weight Setting Success"),
                    ("WEIGHT_SETTING_FAILURE", "Weight Setting Failure"),
                    ("MINER_ORGANIC_JOB_INFO", "Miner Organic Job Info"),
                    ("MINER_ORGANIC_JOB_FAILURE", "Miner Organic Job Failure"),
                    ("MINER_ORGANIC_JOB_SUCCESS", "Miner Organic Job Success"),
                    ("MINER_SYNTHETIC_JOB_SUCCESS", "Miner Synthetic Job Success"),
                    ("MINER_SYNTHETIC_JOB_FAILURE", "Miner Synthetic Job Failure"),
                    ("RECEIPT_FAILURE", "Receipt Failure"),
                    ("FACILITATOR_CLIENT_ERROR", "Facilitator Client Error"),
                    ("VALIDATOR_MINERS_REFRESH", "Validator Miners Refresh"),
                    ("VALIDATOR_SYNTHETIC_JOBS_FAILURE", "Validator Synthetic Jobs Failure"),
                    ("VALIDATOR_FAILURE", "Validator Failure"),
                    ("VALIDATOR_TELEMETRY", "Validator Telemetry"),
                    ("VALIDATOR_CHANNEL_LAYER_ERROR", "Validator Channel Layer Error"),
                    ("VALIDATOR_SYNTHETIC_JOB_SCHEDULED", "Validator Synthetic Job Scheduled"),
                    (
                        "VALIDATOR_OVERSLEPT_SCHEDULED_JOB_WARNING",
                        "Validator Overslept Scheduled Job Warning",
                    ),
                    ("LLM_PROMPT_GENERATION", "Llm Prompt Generation"),
                    ("LLM_PROMPT_ANSWERING", "Llm Prompt Answering"),
                    ("LLM_PROMPT_SAMPLING", "Llm Prompt Sampling"),
                    ("BURNING_INCENTIVE", "Burning Incentive"),
                    ("COMPUTE_TIME_ALLOWANCE", "Compute Time Allowance"),
                    ("METAGRAPH_SYNCING", "Metagraph Syncing"),
                ],
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="ComputeTimeAllowance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "initial_allowance",
                    models.FloatField(
                        default=0.0,
                        help_text="Executor-seconds allocated at the beginning of the cycle",
                    ),
                ),
                (
                    "remaining_allowance",
                    models.FloatField(
                        default=0.0, help_text="Remaining executor-seconds that can be used"
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="validator.cycle"
                    ),
                ),
                (
                    "miner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="validator.miner"
                    ),
                ),
                (
                    "validator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validator_allowances",
                        to="validator.miner",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="computetimeallowance",
            constraint=models.UniqueConstraint(
                fields=("miner", "validator", "cycle"), name="unique_miner_allowance_per_cycle"
            ),
        ),
    ]
