# Generated by Django 4.2.19 on 2025-05-15 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0061_alter_systemevent_subtype"),
        ("validator", "0061_organicjob_upload_results"),
    ]

    operations = []
