# Generated by Django 4.2.19 on 2025-05-12 07:00

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0062_organicjob_slashed_alter_miner_evm_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="miner",
            name="collateral",
        ),
        migrations.AddField(
            model_name="miner",
            name="collateral_wei",
            field=models.DecimalField(decimal_places=0, default=Decimal("0"), max_digits=78),
        ),
    ]
