# Generated by Django 4.2.21 on 2025-05-19 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0062_cycle_set_compute_time_allowance_and_more"),
        ("validator", "0063_alter_systemevent_subtype"),
    ]

    operations = []
