# Generated by Django 4.2.19 on 2025-05-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0064_merge_20250519_1301"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicjob",
            name="streaming_details",
            field=models.JSONField(default=None, null=True),
        ),
    ]
