# Generated by Django 4.2.19 on 2025-05-20 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0063_remove_miner_collateral_miner_collateral_wei"),
        ("validator", "0064_merge_20250519_1301"),
    ]

    operations = []
