# Generated by Django 4.2.19 on 2025-05-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0067_alter_systemevent_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicjob",
            name="streaming_details",
            field=models.JSONField(default=None, null=True),
        ),
    ]
