# Generated by Django 4.2.19 on 2025-07-01 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0068_organicjob_streaming_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minermanifest",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="validator.syntheticjobbatch",
            ),
        ),
        migrations.AddIndex(
            model_name="minermanifest",
            index=models.Index(fields=["created_at"], name="validator_m_created_d4e887_idx"),
        ),
        migrations.AddIndex(
            model_name="minermanifest",
            index=models.Index(
                fields=["miner", "created_at"], name="validator_m_miner_i_3c9451_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="minermanifest",
            index=models.Index(
                fields=["batch", "created_at"], name="validator_m_batch_i_d5b231_idx"
            ),
        ),
    ]
