# Generated by Django 4.2.19 on 2025-07-28 12:41

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0070_delete_minermanifest_batch_none"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinerSplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("coldkey", models.CharField(db_index=True, max_length=255)),
                ("cycle_start", models.BigIntegerField()),
                ("validator_hotkey", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="metagraphsnapshot",
            name="coldkeys",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="miner",
            name="coldkey",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="MinerSplitDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hotkey", models.CharField(max_length=255)),
                ("percentage", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "split",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="validator.minersplit",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="minersplit",
            index=models.Index(
                fields=["coldkey", "cycle_start"], name="validator_m_coldkey_54823d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="minersplit",
            index=models.Index(fields=["validator_hotkey"], name="validator_m_validat_6f5b22_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="minersplit",
            unique_together={("coldkey", "cycle_start", "validator_hotkey")},
        ),
        migrations.AddConstraint(
            model_name="minersplitdistribution",
            constraint=models.CheckConstraint(
                check=models.Q(("percentage__gte", 0), ("percentage__lte", 1)),
                name="valid_percentage_range",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="minersplitdistribution",
            unique_together={("split", "hotkey")},
        ),
    ]
