# Generated by Django 4.2.19 on 2025-08-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0071_minersplit_metagraphsnapshot_coldkeys_miner_coldkey_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinerMainHotkey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("coldkey", models.CharField(db_index=True, max_length=255)),
                ("cycle_start", models.BigIntegerField()),
                ("main_hotkey", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="minersplitdistribution",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="minersplitdistribution",
            name="split",
        ),
        migrations.DeleteModel(
            name="MinerSplit",
        ),
        migrations.DeleteModel(
            name="MinerSplitDistribution",
        ),
        migrations.AddIndex(
            model_name="minermainhotkey",
            index=models.Index(
                fields=["coldkey", "cycle_start"], name="validator_m_coldkey_6de4f1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="minermainhotkey",
            unique_together={("coldkey", "cycle_start")},
        ),
    ]
