# Generated by Django 4.2.19 on 2025-08-10 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0073_allowancebooking_block_mineraddress_neuron_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancebooking',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
