# Generated by Django 4.2.19 on 2025-08-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0073_allowancebooking_block_mineraddress_neuron_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mineraddress",
            name="ip_version",
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
