# Generated by Django 4.2.19 on 2025-08-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0074_mineraddress_ip_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='organicjob',
            name='namespace',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
