# Generated by Django 4.2.19 on 2025-08-10 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0074_mineraddress_ip_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="allowancebooking",
            name="creation_timestamp",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
