# Generated by Django 4.2.19 on 2025-08-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0074_mineraddress_ip_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicjob",
            name="allowance_reservation_id",
            field=models.BigIntegerField(
                blank=True, help_text="ID of the allowance reservation for this job", null=True
            ),
        ),
    ]
