# Generated by Django 4.2.23 on 2025-08-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0075_allowancebooking_creation_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicjob",
            name="allowance_reservation_id",
            field=models.BigIntegerField(
                blank=True, help_text="ID of the allowance reservation for this job", null=True
            ),
        ),
    ]
