# Generated by Django 4.2.23 on 2025-08-25 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0077_remove_cycle_set_compute_time_allowance_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ComputeTimeAllowance",
        ),
    ]
