# Generated by Django 4.2.23 on 2025-08-26 14:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0078_delete_computetimeallowance"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicjob",
            name="allowance_blocks",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.BigIntegerField(), default=list, null=True, size=None
            ),
        ),
    ]
