# Generated by Django 4.2.23 on 2025-09-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0079_organicjob_allowance_blocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicjob",
            name="namespace",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
