# Generated by Django 4.2.19 on 2025-09-08 10:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0081_alter_systemevent_subtype"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinerIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MINER_JOB_REJECTED", "Miner Job Rejected"),
                            ("MINER_JOB_FAILED", "Miner Job Failed"),
                            ("MINER_HORDE_FAILED", "Miner Horde Failed"),
                        ],
                        max_length=255,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("hotkey_ss58address", models.TextField()),
                ("job_uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "executor_class",
                    models.CharField(
                        choices=[
                            ("spin_up-4min.gpu-24gb", "spin_up-4min.gpu-24gb"),
                            ("always_on.gpu-24gb", "always_on.gpu-24gb"),
                            ("always_on.llm.a6000", "always_on.llm.a6000"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="minerincident",
            constraint=models.UniqueConstraint(
                fields=("hotkey_ss58address", "job_uuid"), name="unique_miner_incident"
            ),
        ),
    ]
