# Generated by Django 4.2.19 on 2025-09-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0082_minerincident_minerincident_unique_miner_incident"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="allowancebooking",
            constraint=models.CheckConstraint(
                check=models.Q(("is_reserved", False), ("is_spent", False), _negated=True),
                name="ck_allowance_booking_reserved_or_spent",
            ),
        ),
    ]
