# Generated by Django 4.2.23 on 2025-09-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0082_minerincident_minerincident_unique_miner_incident"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicjob",
            name="allowance_job_value",
            field=models.IntegerField(
                default=0, help_text="The calculated allowance value for this job"
            ),
        ),
    ]
