# Generated by Django 4.2.19 on 2025-09-26 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0083_allowancebooking_ck_allowance_booking_reserved_or_spent"),
        ("validator", "0083_organicjob_allowance_job_value"),
    ]

    operations = []
