# Generated by Django 4.2.19 on 2025-09-26 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0084_merge_20250926_1128"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicjob",
            name="cheated_details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="organicjob",
            name="cheated_message",
            field=models.TextField(blank=True, default="unknown"),
        ),
        migrations.AddField(
            model_name="organicjob",
            name="cheated_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
