# Generated by Django 4.2.19 on 2025-10-01 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0084_merge_20250926_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightSettingFinishedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('block_from', models.BigIntegerField()),
                ('block_to', models.BigIntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='weightsettingfinishedevent',
            constraint=models.UniqueConstraint(fields=('block_from', 'block_to'), name='unique_cycle_in_wsfe'),
        ),
    ]
