# Generated by Django 4.2.19 on 2025-10-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0086_remove_metagraphsnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("WEIGHT_SETTING_INFO", "Weight Setting Info"),
                    ("WEIGHT_SETTING_SUCCESS", "Weight Setting Success"),
                    ("WEIGHT_SETTING_FAILURE", "Weight Setting Failure"),
                    ("MINER_ORGANIC_JOB_INFO", "Miner Organic Job Info"),
                    ("MINER_ORGANIC_JOB_FAILURE", "Miner Organic Job Failure"),
                    ("MINER_ORGANIC_JOB_SUCCESS", "Miner Organic Job Success"),
                    ("MINER_SYNTHETIC_JOB_SUCCESS", "Miner Synthetic Job Success"),
                    ("MINER_SYNTHETIC_JOB_FAILURE", "Miner Synthetic Job Failure"),
                    ("MINER_EXECUTOR_COUNT_CLIPPED", "Miner Executor Count Clipped"),
                    ("RECEIPT_FAILURE", "Receipt Failure"),
                    ("FACILITATOR_CLIENT_ERROR", "Facilitator Client Error"),
                    ("VALIDATOR_MINERS_REFRESH", "Validator Miners Refresh"),
                    ("VALIDATOR_SYNTHETIC_JOBS_FAILURE", "Validator Synthetic Jobs Failure"),
                    ("VALIDATOR_FAILURE", "Validator Failure"),
                    ("VALIDATOR_TELEMETRY", "Validator Telemetry"),
                    ("VALIDATOR_CHANNEL_LAYER_ERROR", "Validator Channel Layer Error"),
                    ("VALIDATOR_SYNTHETIC_JOB_SCHEDULED", "Validator Synthetic Job Scheduled"),
                    (
                        "VALIDATOR_OVERSLEPT_SCHEDULED_JOB_WARNING",
                        "Validator Overslept Scheduled Job Warning",
                    ),
                    ("LLM_PROMPT_GENERATION", "Llm Prompt Generation"),
                    ("LLM_PROMPT_ANSWERING", "Llm Prompt Answering"),
                    ("LLM_PROMPT_SAMPLING", "Llm Prompt Sampling"),
                    ("BURNING_INCENTIVE", "Burning Incentive"),
                    ("COMPUTE_TIME_ALLOWANCE", "Compute Time Allowance"),
                    ("METAGRAPH_SYNCING", "Metagraph Syncing"),
                    ("COLLATERAL_SYNCING", "Collateral Syncing"),
                ],
                max_length=255,
            ),
        ),
    ]
