# Generated by Django 4.2.19 on 2025-10-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0088_metagraphsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="organicjob",
            name="cheat_reported_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="organicjob",
            name="slashed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
