# Generated by Django 4.2.19 on 2025-11-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0090_delete_metagraphsnapshot_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="allowancebooking",
            index=models.Index(
                fields=["is_spent", "is_reserved"], name="validator_a_is_spen_216650_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blockallowance",
            index=models.Index(
                condition=models.Q(("invalidated_at_block__isnull", True)),
                fields=["validator_ss58", "executor_class", "block", "miner_ss58"],
                name="available_block_allowance",
            ),
        ),
        migrations.AddIndex(
            model_name="neuron",
            index=models.Index(fields=["block"], name="validator_n_block_ed14a0_idx"),
        ),
        migrations.AddIndex(
            model_name="neuron",
            index=models.Index(
                fields=["block", "hotkey_ss58address"], name="validator_n_block_1ff139_idx"
            ),
        ),
    ]
