# Generated by Django 4.2.19 on 2025-11-04 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0091_allowancebooking_validator_a_is_spen_216650_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prompt",
            name="sample",
        ),
        migrations.RemoveField(
            model_name="promptsample",
            name="series",
        ),
        migrations.RemoveField(
            model_name="promptsample",
            name="synthetic_job",
        ),
        migrations.RemoveField(
            model_name="promptsample",
            name="workload",
        ),
        migrations.RemoveField(
            model_name="syntheticjob",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="syntheticjob",
            name="miner",
        ),
        migrations.RemoveField(
            model_name="syntheticjobbatch",
            name="cycle",
        ),
        migrations.RemoveConstraint(
            model_name="minermanifest",
            name="unique_miner_manifest",
        ),
        migrations.RemoveIndex(
            model_name="minermanifest",
            name="validator_m_batch_i_d5b231_idx",
        ),
        migrations.RemoveField(
            model_name="minermanifest",
            name="batch",
        ),
        migrations.DeleteModel(
            name="Cycle",
        ),
        migrations.DeleteModel(
            name="Prompt",
        ),
        migrations.DeleteModel(
            name="PromptSample",
        ),
        migrations.DeleteModel(
            name="PromptSeries",
        ),
        migrations.DeleteModel(
            name="SolveWorkload",
        ),
        migrations.DeleteModel(
            name="SyntheticJob",
        ),
        migrations.DeleteModel(
            name="SyntheticJobBatch",
        ),
    ]
