# Generated by Django 4.2.19 on 2025-11-05 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0092_remove_prompt_sample_remove_promptsample_series_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdminJobRequest",
        ),
    ]
