# Generated by Django 4.2.19 on 2025-11-26 13:45
import os

from django.db import migrations


def _remove_shield_certs(apps, schema_editor):
    from django.conf import settings

    try:
        os.remove(str(settings.BITTENSOR_SHIELD_CERTIFICATE_PATH))
    except FileNotFoundError:
        pass
    except OSError:
        print("Failed to remove shield certificate file. Please remove it manually.")


class Migration(migrations.Migration):
    dependencies = [
        ("validator", "0093_delete_adminjobrequest"),
    ]

    operations = [migrations.RunPython(_remove_shield_certs, migrations.RunPython.noop)]
