def test_apiver_exports(apiver_module):
    assert {name for name in dir(apiver_module) if not name.startswith("_")} == {
        "ComputeHordeClient",
        "ComputeHordeError",
        "ComputeHordeHordeFailure",
        "ComputeHordeNotFoundError",
        "ComputeHordeJobTimeoutError",
        "ComputeHordeJobSpec",
        "ComputeHordeJob",
        "ComputeHordeJobFailure",
        "ComputeHordeJobRejection",
        "ComputeHordeJobStatus",
        "ComputeHordeJobStatusEntry",
        "ComputeHordeJobResult",
        "ExecutorClass",
        "HTTPInputVolume",
        "HTTPOutputVolume",
        "HuggingfaceInputVolume",
        "InlineInputVolume",
        "InputVolume",
        "OutputVolume",
    }
