FROM alpine

CMD cat /volume/payload.txt && \
    echo '4 // chosen by fair dice roll. guaranteed to be random :D' > /output/file1.txt && \
    echo '5 // chosen by fair dice roll. guaranteed to be random :D' > /output/file2.txt
