# Instruct themes used in https://arxiv.org/pdf/2304.12244.pdf to train WizardLM
THEMES = [
    "Philosopy",
    "Technology",
    "Physics",
    "Ethics",
    "Academic Writing",
    "Economy",
    "History",
    "Medicine",
    "Toxicity",
    "Roleplay",
    "Entertainment",
    "Biology",
    "Counterfactual",
    "Literature",
    "Chemistry",
    "Writing",
    "Sport",
    "Law",
    "Language",
    "Computer Science",
    "Multilangual",
    "Common Sense",
    "Art",
    "Complex Format",
    "Code Generation",
    "Math",
    "Code Debug",
    "Reasoning",
    "Love and relationships",
    "Nature and environment",
    "Art and creativity",
    "Technology and innovation",
    "Health and wellness",
    "History and culture",
    "Science and discovery",
    "Philosophy and ethics",
    "Education and learning",
    "Music and rhythm",
    "Sports and athleticism",
    "Food and nutrition",
    "Travel and adventure",
    "Fashion and style",
    "Books and literature",
    "Movies and entertainment",
    "Politics and governance",
    "Business and entrepreneurship",
    "Mind and consciousness",
    "Family and parenting",
    "Social media and networking",
    "Religion and spirituality",
    "Money and finance",
    "Language and communication",
    "Human behavior and psychology",
    "Space and astronomy",
    "Climate change and sustainability",
    "Dreams and aspirations",
    "Equality and social justice",
    "Gaming and virtual reality",
    "Artificial intelligence and robotics",
    "Creativity and imagination",
    "Emotions and feelings",
    "Healthcare and medicine",
    "Sportsmanship and teamwork",
    "Cuisine and gastronomy",
    "Historical events and figures",
    "Scientific advancements",
    "Ethical dilemmas and decision making",
    "Learning and growth",
    "Music genres and artists",
    "Film genres and directors",
    "Government policies and laws",
    "Startups and innovation",
    "Consciousness and perception",
    "Parenting styles and techniques",
    "Online communities and forums",
    "Religious practices and rituals",
    "Personal finance and budgeting",
    "Linguistic diversity and evolution",
    "Human cognition and memory",
    "Astrology and horoscopes",
    "Environmental conservation",
    "Personal development and self-improvement",
    "Sports strategies and tactics",
    "Culinary traditions and customs",
    "Ancient civilizations and empires",
    "Medical breakthroughs and treatments",
    "Moral values and principles",
    "Critical thinking and problem solving",
    "Musical instruments and techniques",
    "Film production and cinematography",
    "International relations and diplomacy",
    "Corporate culture and work-life balance",
    "Neuroscience and brain function",
    "Childhood development and milestones",
    "Online privacy and cybersecurity",
    "Religious tolerance and understanding",
    "Investment strategies and tips",
    "Language acquisition and fluency",
    "Social influence and conformity",
    "Space exploration and colonization",
    "Sustainable living and eco-friendly practices",
    "Self-reflection and introspection",
    "Sports psychology and mental training",
    "Globalization and cultural exchange",
    "Political ideologies and systems",
    "Entrepreneurial mindset and success",
    "Conscious living and mindfulness",
    "Positive psychology and happiness",
    "Music therapy and healing",
    "Film analysis and interpretation",
    "Human rights and advocacy",
    "Financial literacy and money management",
    "Multilingualism and translation",
    "Social media impact on society",
    "Religious extremism and radicalization",
    "Real estate investment and trends",
    "Language preservation and revitalization",
    "Social inequality and discrimination",
    "Climate change mitigation strategies",
    "Self-care and well-being",
    "Sports injuries and rehabilitation",
    "Artificial intelligence ethics",
    "Creativity in problem solving",
    "Emotional intelligence and empathy",
    "Healthcare access and affordability",
    "Sports analytics and data science",
    "Cultural appropriation and appreciation",
    "Ethical implications of technology" "Virtual reality and simulation",
    "Quantum physics and mechanics",
    "Sustainable agriculture and farming",
    "Renewable energy and resources",
    "Climate adaptation and resilience",
    "Biodiversity and conservation",
    "Mental health and wellness",
    "Diversity and inclusion",
    "Human rights and social justice",
    "Global health and pandemics",
    "Data privacy and ethics",
    "Blockchain and cryptocurrencies",
    "Internet of Things and smart devices",
    "Machine learning and data science",
    "Space travel and extraterrestrial life",
    "Nanotechnology and materials science",
    "Biotechnology and genetic engineering",
    "Artificial general intelligence",
    "Cybersecurity and digital warfare",
    "Urban planning and smart cities",
    "Digital art and design",
    "Cognitive science and artificial intelligence",
    "Futurism and technology trends",
    "Education technology and digital learning",
    "Food technology and innovation",
    "Sustainable fashion and textiles",
    "Green architecture and design",
    "Digital marketing and e-commerce",
    "Social entrepreneurship and impact",
    "Cultural heritage and preservation",
    "Indigenous knowledge and wisdom",
    "Gender studies and feminism",
    "Posthumanism and transhumanism",
    "Existential risk and catastrophe",
    "Philosophy of mind and consciousness",
    "Ethics of artificial intelligence",
    "Psychedelics and consciousness",
    "Meditation and mindfulness",
    "Yoga and holistic health",
    "Nutrition and diet",
    "Fitness and exercise",
    "Aging and longevity",
    "Neuroplasticity and brain health",
    "Sleep and dreams",
    "Emotional intelligence and resilience",
    "Stress management and relaxation",
    "Happiness and positive psychology",
    "Love and relationships",
    "Parenting and child development",
    "Personal growth and self-improvement",
    "Creativity and innovation",
    "Motivation and productivity",
    "Leadership and management",
    "Communication and negotiation",
    "Career development and job skills",
    "Financial literacy and wealth management",
    "Investing and personal finance",
    "Entrepreneurship and startups",
    "Marketing and branding",
    "Sales and negotiation",
    "Strategy and competition",
    "Organizational culture and teamwork",
    "Project management and agile",
    "Innovation and disruption",
    "Business ethics and corporate social responsibility",
    "Economics and globalization",
    "Politics and diplomacy",
    "Law and justice",
    "History and archaeology",
    "Philosophy and critical thinking",
    "Literature and writing",
    "Art and aesthetics",
    "Music and dance",
    "Film and cinema",
    "Photography and visual arts",
    "Design and architecture",
    "Fashion and style",
    "Cuisine and gastronomy",
    "Travel and adventure",
    "Sports and games",
    "Nature and environment",
    "Animals and wildlife",
    "Gardening and horticulture",
    "Astronomy and space exploration",
    "Physics and chemistry",
    "Biology and life sciences",
    "Mathematics and logic",
    "Computer science and programming",
    "Engineering and technology",
    "Medicine and healthcare",
    "Psychology and neuroscience",
    "Sociology and anthropology",
    "Geography and earth sciences",
    "Climate change and sustainability",
    "Conservation and ecology",
    "Renewable energy and green technology",
    "Humanitarian aid and disaster relief",
    "Peace and conflict resolution",
    "Democracy and human rights",
    "Accountancy",
    "Anthropology",
    "Applied Mathematics",
    "Architecture",
    "Art",
    "Artificial Intelligence",
    "Bioengineering",
    "Biological Sciences",
    "Biotechnology",
    "Business Administration",
    "Chemical Engineering",
    "Chemistry",
    "Civil Engineering",
    "Classical Studies",
    "Cognitive Science",
    "Communication",
    "Computer Engineering",
    "Computer Science",
    "Criminal Justice",
    "Cybersecurity",
    "Data Analysis",
    "Dentistry",
    "Design",
    "Economics",
    "Education",
    "Electrical Engineering",
    "English Literature",
    "Environmental Science",
    "Epidemiology",
    "Ethics",
    "Film Production",
    "Finance",
    "Forensic Science",
    "Genetics",
    "Geography",
    "Geology",
    "Graphic Design",
    "History",
    "Hospitality Management",
    "Human Resources Management",
    "Immunology",
    "Industrial Design",
    "Information Systems",
    "Information Technology",
    "International Relations",
    "Journalism",
    "Law",
    "Linguistics",
    "Management",
    "Marketing",
    "Materials Science",
    "Mathematics",
    "Mechanical Engineering",
    "Media Studies",
    "Medicine",
    "Microbiology",
    "Music Performance",
    "Nursing",
    "Nutrition",
    "Occupational Therapy",
    "Pharmacology",
    "Philosophy",
    "Physics",
    "Political Science",
    "Psychology",
    "Public Health",
    "Public Policy",
    "Real Estate",
    "Religious Studies",
    "Robotics",
    "Social Work",
    "Sociology",
    "Software Development",
    "Statistics",
    "Theater",
    "Urban Planning",
    "Veterinary Medicine",
    "Visual Arts",
    "Web Development",
    "Zoology",
    "Astronomy",
    "Astrophysics",
    "Biochemistry",
    "Bioinformatics",
    "Biology",
    "Biophysics",
    "Botany",
    "Chemical Engineering",
    "Chemistry",
    "Climatology",
    "Computational Biology",
    "Computer Science",
    "Conservation Biology",
    "Data Science",
    "Ecology",
    "Environmental Science",
    "Epidemiology",
    "Genetics",
    "Geology",
    "Geophysics",
    "Immunology",
    "Marine Biology",
    "Materials Science",
    "Mathematics",
    "Mechanical Engineering",
    "Microbiology",
    "Molecular Biology",
    "Neuroscience",
    "Nuclear Physics",
    "Oceanography",
    "Organic Chemistry",
    "Paleontology",
    "Pathology",
    "Pharmacology",
    "Physics",
    "Physiology",
    "Planetary Science",
    "Plant Science",
    "Quantum Physics",
    "Software Engineering",
    "Statistics",
    "Systems Biology",
    "Theoretical Physics",
    "Toxicology",
    "Virology",
    "Zoology",
    "Artificial Intelligence",
    "Machine Learning",
    "Network Science",
    "Cognitive Science",
    "Cybersecurity",
    "Developmental Biology",
    "Environmental Engineering",
    "Evolutionary Biology",
    "Forensic Science",
    "Genomics",
    "Hydrology",
    "Meteorology",
    "Microelectronics",
    "Nanotechnology",
    "Neuropsychology",
    "Optics",
    "Pharmaceutical Sciences",
    "Physical Chemistry",
    "Quantum Computing",
    "Renewable Energy",
    "Robotics",
    "Software Development",
    "Structural Biology",
    "Synthetic Biology",
    "Web Development",
    "Aerospace Engineering",
    "Agricultural Science",
    "Anatomy",
    "Animal Science",
    "Atmospheric Sciences",
    "Biomedical Engineering",
    "Cell Biology",
    "Cognitive Neuroscience",
    "Computational Chemistry",
    "Cryogenics",
    "Earth Science",
    "Electrical Engineering",
    "Entomology",
    "Genetic Engineering",
    "Geography",
    "Human-Computer Interaction",
    "Immunotherapy",
    "Industrial Engineering",
    "Information Theory",
    "Inorganic Chemistry",
    "Logic",
    "Mathematical Biology",
    "Mycology",
    "Operational Research",
    "Paleoecology",
    "Physical Oceanography",
    "Plant Pathology",
    "Psychophysics",
    "Public Health",
    "Quantum Mechanics",
    "Seismology",
    "Sociobiology",
    "Soil Science",
    "Space Science",
    "Spectroscopy",
    "Thermodynamics",
    "Vaccinology",
    "Veterinary Medicine",
    "Allergy and immunology",
    "Anesthesiology",
    "Cardiology",
    "Dermatology",
    "Emergency medicine",
    "Endocrinology",
    "Family medicine",
    "Gastroenterology",
    "General surgery",
    "Geriatrics",
    "Hematology",
    "Infectious disease",
    "Internal medicine",
    "Medical genetics",
    "Nephrology",
    "Neurology",
    "Neurosurgery",
    "Obstetrics and gynecology",
    "Oncology",
    "Ophthalmology",
    "Orthopedic surgery",
    "Otolaryngology (ENT)",
    "Pathology",
    "Pediatrics",
    "Physical medicine and rehabilitation",
    "Plastic surgery",
    "Psychiatry",
    "Pulmonology",
    "Radiology",
    "Rheumatology",
    "Sports medicine",
    "Thoracic surgery",
    "Urology",
    "Vascular surgery",
    "Pain management",
    "Palliative care",
    "Critical care medicine",
    "Occupational medicine",
    "Public health and preventive medicine",
    "Radiation oncology",
    "Reproductive endocrinology and infertility",
    "Sleep medicine",
    "Transplant hepatology",
    "Tropical medicine",
    "Urgent care medicine",
    "Addiction medicine",
    "Cardiothoracic surgery",
    "Clinical pharmacology",
    "Dental surgery",
    "Dermatopathology",
    "Developmental-behavioral pediatrics",
    "Forensic pathology",
    "Gynecologic oncology",
    "Hand surgery",
    "Head and neck surgery",
    "Hospice and palliative medicine",
    "Interventional cardiology",
    "Maternal-fetal medicine",
    "Medical toxicology",
    "Neonatal-perinatal medicine",
    "Nuclear medicine",
    "Orthopedic sports medicine",
    "Prosthodontics",
    "Psychosomatic medicine",
    "Retinal surgery",
    "Spinal surgery",
    "Surgical oncology",
    "Trauma surgery",
    "Vascular neurology" "Accounting",
    "Acting",
    "Architecture",
    "Astronomy",
    "Biology",
    "Carpentry",
    "Cooking",
    "Dancing",
    "Dentistry",
    "Economics",
    "Engineering",
    "Farming",
    "Fashion design",
    "Film making",
    "Graphic design",
    "Historiography",
    "Journalism",
    "Law",
    "Marketing",
    "Medicine",
    "Music composition",
    "Nursing",
    "Painting",
    "Pharmacy",
    "Photography",
    "Physics",
    "Piloting",
    "Plumbing",
    "Programming",
    "Psychology",
    "Research",
    "Sculpting",
    "Singing",
    "Social work",
    "Teaching",
    "Veterinary medicine",
    "Writing",
    "Zoology",
    "Web design",
    "Videography",
    "Urban planning",
    "Translation",
    "Theology",
    "Surveying",
    "Statistical analysis",
    "Software development",
    "Ski instructing",
    "Shipbuilding",
    "SEO (Search Engine Optimization)",
    "Security analysis",
    "Screenwriting",
    "Sales",
    "Public relations",
    "Project management",
    "Product design",
    "Physical therapy",
    "Personal training",
    "Performing arts",
    "Pediatrics",
    "Pathology",
    "Partnership development",
    "Optometry",
    "Occupational therapy",
    "Nutrition",
    "Meteorology",
    "Mechanics",
    "Massage therapy",
    "Masonry",
    "Logistics",
    "Linguistics",
    "Interior design",
    "Industrial design",
    "Illustration",
    "Hydrology",
    "Horticulture",
    "Geology",
    "Forestry",
    "Floristry",
    "Fishery",
    "Financial analysis",
    "Fashion modeling",
    "Environmental science",
    "Entomology",
    "Electrical engineering",
    "Ecology",
    "Dermatology",
    "Criminal investigation",
    "Counseling",
    "Construction",
    "Conservation biology",
    "Computational science",
    "Civil engineering",
    "Chemistry",
    "Cartography",
    "Carpentry",
    "Career counseling",
    "Business consulting",
    "Building",
    "Broadcasting",
    "Bookkeeping",
    "Biotechnology",
    "Audiology",
    "Art restoration",
    "Art direction",
    "Archaeology",
    "Animation",
    "Anesthesiology",
    "Analytics" "Celebrities",
    "Fashion",
    "Music",
    "Movies",
    "Television shows",
    "Social media trends",
    "Video games",
    "Memes",
    "Internet culture",
    "Fan communities",
    "Pop music",
    "Reality TV",
    "Streaming services",
    "Influencers",
    "Comic books",
    "Anime and manga",
    "Superheroes",
    "Fantasy and science fiction",
    "Award shows",
    "Film festivals",
    "Pop art",
    "Street art",
    "Dance",
    "Theatre",
    "Podcasts",
    "Literature",
    "Graphic novels",
    "Viral videos",
    "Celebrity fashion",
    "Music festivals",
    "Fan conventions",
    "Cosplay",
    "Pop culture criticism",
    "Nostalgia and retro culture",
    "Emerging artists",
    "Trending technologies in entertainment",
    "Crossover media",
    "Pop culture merchandise",
    "Aviation",
    "Cars",
    "Cycling",
    "Public transport",
    "Rail transport",
    "Road transport",
    "Shipping",
    "Spaceflight",
    "Vehicles",
    "Water transport" "Electronics",
    "Avionics",
    "Circuits",
    "Companies",
    "Connectors",
    "Consumer electronics",
    "Digital electronics",
    "Digital media",
    "Electrical components",
    "Electronic design",
    "Electronics manufacturing",
    "Embedded systems",
    "Integrated circuits",
    "Microwave technology",
    "Molecular electronics",
    "Water technology",
    "Optoelectronics",
    "Quantum electronics",
    "Radio-frequency identification (RFID)",
    "Radio electronics",
    "Semiconductors",
    "Signal cables",
    "Surveillance",
    "Telecommunications",
    "Engineering",
    "Aerospace engineering",
    "Bioengineering",
    "Chemical engineering",
    "Civil engineering",
    "Electrical engineering",
    "Environmental engineering",
    "Materials science",
    "Mechanical engineering",
    "Nuclear technology",
    "Software engineering",
    "Structural engineering",
    "Systems engineering",
    "Computing",
    "Apps",
    "Artificial intelligence",
    "Classes of computers",
    "Companies",
    "Computer architecture",
    "Computer model",
    "Computer engineering",
    "Computer science",
    "Computer security",
    "Computing and society",
    "Data",
    "Embedded systems",
    "Free software",
    "Human–computer interaction",
    "Information systems",
    "Information technology",
    "Internet",
    "Mobile web",
    "Languages",
    "Multimedia",
    "Networks (Industrial)",
    "Operating systems",
    "Platforms",
    "Product lifecycle management",
    "Programming",
    "Real-time computing",
    "Software",
    "Software engineering",
    "Unsolved problems in computer science",
    "Agriculture",
    "Agronomy",
    "Architecture",
    "Automation",
    "Biotechnology",
    "Cartography",
    "Chemical engineering",
    "Communication",
    "Media studies",
    "Telecommunications",
    "Construction",
    "Control theory",
    "Design",
    "Digital divide",
    "Earthquake engineering",
    "Energy",
    "Ergonomics",
    "Firefighting",
    "Fire prevention",
    "Forensic science",
    "Forestry",
    "Industry",
    "Information science",
    "Internet",
    "Management",
    "Manufacturing",
    "Marketing",
    "Medicine",
    "Unsolved problems in neuroscience",
    "Metalworking",
    "Microtechnology",
    "Military science",
    "Mining",
    "Nanotechnology",
    "Nuclear technology",
    "Optics",
    "Plumbing",
    "Robotics",
    "Sound technology",
    "Technology forecasting",
    "Tools",
    "Society",
    "Activism",
    "Business",
    "Communication",
    "Crime",
    "Education",
    "Ethnic groups",
    "Family",
    "Finance",
    "Globalization",
    "Government",
    "Health",
    "Home",
    "Industries",
    "Infrastructure",
    "Law",
    "Mass media",
    "Military",
    "Money",
    "Organizations",
    "Peace",
    "Politics",
    "Real estate",
    "Rights",
    "War",
    "Social sciences",
    "Anthropology",
    "Archaeology",
    "Cultural studies",
    "Demographics",
    "Economics",
    "Information science",
    "International relations",
    "Linguistics",
    "Media studies",
    "Political science",
    "Psychology",
    "Public administration",
    "Sexology",
    "Social scientists",
    "Sociology",
    "Social work",
    "Systems theory",
    "Allah",
    "Bible",
    "Buddhas",
    "Deities",
    "Demons",
    "Exorcism",
    "God",
    "Jesus",
    "Mythology",
    "Occult",
    "Prayer",
    "Prophecy",
    "Quran",
    "Religious ethics",
    "Religious law",
    "Ritual",
    "Spirituality",
    "Theology",
    "Belief systems",
    "Religious faiths, traditions, and movements",
    "Agnosticism",
    "Animism",
    "Atheism",
    "Deism",
    "Determinism",
    "Esotericism",
    "Gnosticism",
    "Humanism",
    "Monism",
    "Monotheism",
    "Mysticism",
    "New Age",
    "Paganism",
    "Pantheism",
    "Polytheism",
    "Shamanism",
    "Skepticism",
    "Spiritualism",
    "Theosophy",
    "Transcendentalism",
    "Unitarianism",
    "Major beliefs of the world",
    "Ayyavazhi",
    "Bahá'í Faith",
    "Buddhism",
    "Caodaism",
    "Chinese folk religion",
    "Christianity",
    "Confucianism",
    "Druidry",
    "Falun Gong",
    "Hinduism",
    "Islam",
    "Jainism",
    "Judaism",
    "Modern paganism",
    "Mormonism",
    "Neo-druidism",
    "Rastafarianism",
    "Satanism",
    "Scientology",
    "Shinto",
    "Sikhism",
    "Spiritism",
    "Taoism",
    "Tenrikyo",
    "Unitarian Universalism",
    "Wicca",
    "Zoroastrianism",
    "Mythology by culture",
    "Buddhist mythology",
    "Christian mythology",
    "Hindu mythology",
    "Islamic mythology",
    "Jewish mythology",
    "Branches",
    "Schools and traditions",
    "Concepts",
    "Theories",
    "Arguments",
    "Philosophers",
    "Literature",
    "History",
    "Aesthetics",
    "Epistemology",
    "Ethics",
    "Logic",
    "Metaphysics",
    "Social philosophy",
    "Thinking / Thinking skills",
    "Attention",
    "Cognition",
    "Cognitive biases",
    "Creativity",
    "Decision theory",
    "Emotion",
    "Error",
    "Imagination",
    "Intelligence researchers",
    "Learning",
    "Memory biases",
    "mnemonics",
    "Nootropics (smart drugs)",
    "Organizational thinking (strategic management)",
    "Perception",
    "Problem solving",
    "Psychological adjustment",
    "Psychometrics",
    "Self",
    "Alter egos",
    "Consciousness",
    "Gender",
    "Personality",
    "Sexuality",
    "Sexual orientation",
    "Personal life",
    "Clothing",
    "Employment",
    "Entertainment",
    "Food and drink",
    "Games",
    "Health",
    "Hobbies",
    "Home",
    "Income",
    "Interpersonal relationships",
    "Leisure",
    "Love",
    "Motivation",
    "Personal development",
    "Pets",
    "Activists",
    "Actors",
    "Astronauts",
    "Billionaires",
    "Chief executive officers",
    "Composers",
    "Cyborgs",
    "Defectors",
    "Generals",
    "Inventors",
    "Lesbian, gay, bisexual or transgender (LGBT) people",
    "Monarchs",
    "Musicians",
    "Musical groups",
    "Philanthropists",
    "Philosophers",
    "Photographers",
    "Politicians",
    "Presidents",
    "Princes",
    "Princesses",
    "Revolutionaries",
    "Scientists",
    "Settlers",
    "Singers",
    "Slaves",
    "Victims",
    "People associated with war",
    "Writers",
    "Biology",
    "Botany",
    "Ecology",
    "Health sciences",
    "Medicine",
    "Neuroscience",
    "Zoology",
    "See also the Health and fitness section above",
    "Earth sciences",
    "Atmospheric sciences",
    "Geography",
    "Geology",
    "Geophysics",
    "Oceanography",
    "Nature",
    "Animals",
    "Environment",
    "Humans",
    "Life",
    "Natural resources",
    "Plants",
    "Pollution",
    "Physical sciences",
    "Astronomy",
    "Chemistry",
    "Climate",
    "Physics",
    "Space",
    "Universe",
    "Scientific method",
    "Scientists",
    "Mathematics",
    "Mathematics education",
    "Equations",
    "Heuristics",
    "Measurement",
    "Numbers",
    "Proofs",
    "Theorems",
    "Fields of mathematics",
    "Arithmetic",
    "Algebra",
    "Geometry",
    "Trigonometry",
    "Mathematical analysis",
    "Calculus",
    "Logic",
    "Deductive reasoning",
    "Inductive reasoning",
    "History of logic",
    "Fallacies",
    "Metalogic",
    "Philosophy of logic",
    "Mathematical sciences",
    "Computational science",
    "Operations research",
    "Theoretical physics",
    "Statistics",
    "Analysis of variance",
    "Bayesian statistics",
    "Categorical data",
    "Covariance and correlation",
    "Data analysis",
    "Decision theory",
    "Design of experiments",
    "Logic and statistics",
    "Multivariate statistics",
    "Non-parametric statistics",
    "Parametric statistics",
    "Regression analysis",
    "Sampling",
    "Statistical theory",
    "Stochastic processes",
    "Summary statistics",
    "Survival analysis",
    "Time series",
    "Activism",
    "Agriculture",
    "Arts",
    "Aviation",
    "Commemoration",
    "Communication",
    "Crime",
    "Design",
    "Education",
    "Entertainment",
    "Fictional activities",
    "Fishing",
    "Food and drink preparation",
    "Government",
    "Hunting",
    "Industry",
    "Leisure activities",
    "Navigation",
    "Observation",
    "Performing arts",
    "Physical exercise",
    "Planning",
    "Politics",
    "Recreation",
    "Religion",
    "Human spaceflight",
    "Sports",
    "Trade",
    "Transport",
    "Travel",
    "Underwater human activities",
    "Underwater diving",
    "War",
    "Work",
    "Mathematics",
    "Mathematics education",
    "Equations",
    "Heuristics",
    "Measurement",
    "Numbers",
    "Proofs",
    "Theorems",
    "Fields of mathematics",
    "Arithmetic",
    "Algebra",
    "Geometry",
    "Trigonometry",
    "Mathematical analysis",
    "Calculus",
    "Logic",
    "Deductive reasoning",
    "Inductive reasoning",
    "History of logic",
    "Fallacies",
    "Metalogic",
    "Philosophy of logic",
    "Mathematical sciences",
    "Computational science",
    "Operations research",
    "Theoretical physics",
    "Statistics",
    "Analysis of variance",
    "Bayesian statistics",
    "Categorical data",
    "Covariance and correlation",
    "Data analysis",
    "Decision theory",
    "Design of experiments",
    "Logic and statistics",
    "Multivariate statistics",
    "Non-parametric statistics",
    "Parametric statistics",
    "Regression analysis",
    "Sampling",
    "Statistical theory",
    "Stochastic processes",
    "Summary statistics",
    "Survival analysis",
    "Time series",
    "Biology",
    "Botany",
    "Ecology",
    "Health sciences",
    "Medicine",
    "Neuroscience",
    "Zoology",
    "See also the Health and fitness section above",
    "Earth sciences",
    "Atmospheric sciences",
    "Geography",
    "Geology",
    "Geophysics",
    "Oceanography",
    "Nature",
    "Animals",
    "Environment",
    "Humans",
    "Life",
    "Natural resources",
    "Plants",
    "Pollution",
    "Physical sciences",
    "Astronomy",
    "Chemistry",
    "Climate",
    "Physics",
    "Space",
    "Universe",
    "Scientific method",
    "Scientists",
    "Activists",
    "Actors",
    "Astronauts",
    "Billionaires",
    "Chief executive officers",
    "Composers",
    "Cyborgs",
    "Defectors",
    "Generals",
    "Inventors",
    "Lesbian, gay, bisexual or transgender (LGBT) people",
    "Monarchs",
    "Musicians",
    "Musical groups",
    "Philanthropists",
    "Philosophers",
    "Photographers",
    "Politicians",
    "Presidents",
    "Princes",
    "Princesses",
    "Revolutionaries",
    "Scientists",
    "Settlers",
    "Singers",
    "Slaves",
    "Victims",
    "People associated with war",
    "Writers",
    "Self",
    "Alter egos",
    "Consciousness",
    "Gender",
    "Personality",
    "Sexuality",
    "Sexual orientation",
    "Personal life",
    "Clothing",
    "Employment",
    "Entertainment",
    "Food and drink",
    "Games",
    "Health",
    "Hobbies",
    "Home",
    "Income",
    "Interpersonal relationships",
    "Leisure",
    "Love",
    "Motivation",
    "Personal development",
    "Pets",
    "Aesthetics",
    "Epistemology",
    "Ethics",
    "Logic",
    "Metaphysics",
    "Social philosophy",
    "Thinking / Thinking skills",
    "Attention",
    "Cognition",
    "Cognitive biases",
    "Creativity",
    "Decision theory",
    "Emotion",
    "Error",
    "Imagination",
    "Intelligence researchers",
    "Learning",
    "Memory biases",
    "mnemonics",
    "Nootropics (smart drugs)",
    "Organizational thinking (strategic management)",
    "Perception",
    "Problem solving",
    "Psychological adjustment",
    "Psychometrics",
    "Allah",
    "Bible",
    "Buddhas",
    "Deities",
    "Demons",
    "Exorcism",
    "God",
    "Jesus",
    "Mythology",
    "Occult",
    "Prayer",
    "Prophecy",
    "Quran",
    "Religious ethics",
    "Religious law",
    "Ritual",
    "Spirituality",
    "Theology",
    "Belief systems",
    "Religious faiths, traditions, and movements",
    "Agnosticism",
    "Animism",
    "Atheism",
    "Deism",
    "Determinism",
    "Esotericism",
    "Gnosticism",
    "Humanism",
    "Monism",
    "Monotheism",
    "Mysticism",
    "New Age",
    "Paganism",
    "Pantheism",
    "Polytheism",
    "Shamanism",
    "Skepticism",
    "Spiritualism",
    "Theosophy",
    "Transcendentalism",
    "Unitarianism",
    "Major beliefs of the world",
    "Ayyavazhi",
    "Bahá'í Faith",
    "Buddhism",
    "Caodaism",
    "Chinese folk religion",
    "Christianity",
    "Confucianism",
    "Druidry",
    "Falun Gong",
    "Hinduism",
    "Islam",
    "Jainism",
    "Judaism",
    "Modern paganism",
    "Mormonism",
    "Neo-druidism",
    "Rastafarianism",
    "Satanism",
    "Scientology",
    "Shinto",
    "Sikhism",
    "Spiritism",
    "Taoism",
    "Tenrikyo",
    "Unitarian Universalism",
    "Wicca",
    "Zoroastrianism",
    "Mythology by culture",
    "Buddhist mythology",
    "Christian mythology",
    "Hindu mythology",
    "Islamic mythology",
    "Jewish mythology",
    "Society",
    "Activism",
    "Business",
    "Communication",
    "Crime",
    "Education",
    "Ethnic groups",
    "Family",
    "Finance",
    "Globalization",
    "Government",
    "Health",
    "Home",
    "Industries",
    "Infrastructure",
    "Law",
    "Mass media",
    "Military",
    "Money",
    "Organizations",
    "Peace",
    "Politics",
    "Real estate",
    "Rights",
    "War",
    "Social sciences",
    "Anthropology",
    "Archaeology",
    "Cultural studies",
    "Demographics",
    "Economics",
    "Information science",
    "International relations",
    "Linguistics",
    "Media studies",
    "Political science",
    "Psychology",
    "Public administration",
    "Sexology",
    "Social scientists",
    "Sociology",
    "Social work",
    "Systems theory",
    "Agriculture",
    "Agronomy",
    "Architecture",
    "Automation",
    "Biotechnology",
    "Cartography",
    "Chemical engineering",
    "Communication",
    "Media studies",
    "Telecommunications",
    "Construction",
    "Control theory",
    "Design",
    "Digital divide",
    "Earthquake engineering",
    "Energy",
    "Ergonomics",
    "Firefighting",
    "Fire prevention",
    "Forensic science",
    "Forestry",
    "Industry",
    "Information science",
    "Internet",
    "Management",
    "Manufacturing",
    "Marketing",
    "Medicine",
    "Unsolved problems in neuroscience",
    "Metalworking",
    "Microtechnology",
    "Military science",
    "Mining",
    "Nanotechnology",
    "Nuclear technology",
    "Optics",
    "Plumbing",
    "Robotics",
    "Sound technology",
    "Technology forecasting",
    "Tools",
    "Accounting",
    "Acting",
    "Architecture",
    "Astronomy",
    "Biology",
    "Carpentry",
    "Cooking",
    "Dancing",
    "Dentistry",
    "Economics",
    "Engineering",
    "Farming",
    "Fashion design",
    "Film making",
    "Graphic design",
    "Historiography",
    "Journalism",
    "Law",
    "Marketing",
    "Medicine",
    "Music composition",
    "Nursing",
    "Painting",
    "Pharmacy",
    "Photography",
    "Physics",
    "Piloting",
    "Plumbing",
    "Programming",
    "Psychology",
    "Research",
    "Sculpting",
    "Singing",
    "Social work",
    "Teaching",
    "Veterinary medicine",
    "Writing",
    "Zoology",
    "Web design",
    "Videography",
    "Urban planning",
    "Translation",
    "Theology",
    "Surveying",
    "Statistical analysis",
    "Software development",
    "Ski instructing",
    "Shipbuilding",
    "SEO (Search Engine Optimization)",
    "Security analysis",
    "Screenwriting",
    "Sales",
    "Public relations",
    "Project management",
    "Product design",
    "Physical therapy",
    "Personal training",
    "Performing arts",
    "Pediatrics",
    "Pathology",
    "Partnership development",
    "Optometry",
    "Occupational therapy",
    "Nutrition",
    "Meteorology",
    "Mechanics",
    "Massage therapy",
    "Masonry",
    "Logistics",
    "Linguistics",
    "Interior design",
    "Industrial design",
    "Illustration",
    "Hydrology",
    "Horticulture",
    "Geology",
    "Forestry",
    "Floristry",
    "Fishery",
    "Financial analysis",
    "Fashion modeling",
    "Environmental science",
    "Entomology",
    "Electrical engineering",
    "Ecology",
    "Dermatology",
    "Criminal investigation",
    "Counseling",
    "Construction",
    "Conservation biology",
    "Computational science",
    "Civil engineering",
    "Chemistry",
    "Cartography",
    "Carpentry",
    "Career counseling",
    "Business consulting",
    "Building",
    "Broadcasting",
    "Bookkeeping",
    "Biotechnology",
    "Audiology",
    "Art restoration",
    "Art direction",
    "Archaeology",
    "Animation",
    "Anesthesiology",
    "Analytics",
    "Allergy and immunology",
    "Anesthesiology",
    "Cardiology",
    "Dermatology",
    "Emergency medicine",
    "Endocrinology",
    "Family medicine",
    "Gastroenterology",
    "General surgery",
    "Geriatrics",
    "Hematology",
    "Infectious disease",
    "Internal medicine",
    "Medical genetics",
    "Nephrology",
    "Neurology",
    "Neurosurgery",
    "Obstetrics and gynecology",
    "Oncology",
    "Ophthalmology",
    "Orthopedic surgery",
    "Otolaryngology (ENT)",
    "Pathology",
    "Pediatrics",
    "Physical medicine and rehabilitation",
    "Plastic surgery",
    "Psychiatry",
    "Pulmonology",
    "Radiology",
    "Rheumatology",
    "Sports medicine",
    "Thoracic surgery",
    "Urology",
    "Vascular surgery",
    "Pain management",
    "Palliative care",
    "Critical care medicine",
    "Occupational medicine",
    "Public health and preventive medicine",
    "Radiation oncology",
    "Reproductive endocrinology and infertility",
    "Sleep medicine",
    "Transplant hepatology",
    "Tropical medicine",
    "Urgent care medicine",
    "Addiction medicine",
    "Cardiothoracic surgery",
    "Clinical pharmacology",
    "Dental surgery",
    "Dermatopathology",
    "Developmental-behavioral pediatrics",
    "Forensic pathology",
    "Gynecologic oncology",
    "Hand surgery",
    "Head and neck surgery",
    "Hospice and palliative medicine",
    "Interventional cardiology",
    "Maternal-fetal medicine",
    "Medical toxicology",
    "Neonatal-perinatal medicine",
    "Nuclear medicine",
    "Orthopedic sports medicine",
    "Prosthodontics",
    "Psychosomatic medicine",
    "Retinal surgery",
    "Spinal surgery",
    "Surgical oncology",
    "Trauma surgery",
    "Vascular neurology",
    "Astronomy",
    "Astrophysics",
    "Biochemistry",
    "Bioinformatics",
    "Biology",
    "Biophysics",
    "Botany",
    "Chemical Engineering",
    "Chemistry",
    "Climatology",
    "Computational Biology",
    "Computer Science",
    "Conservation Biology",
    "Data Science",
    "Ecology",
    "Environmental Science",
    "Epidemiology",
    "Genetics",
    "Geology",
    "Geophysics",
    "Immunology",
    "Marine Biology",
    "Materials Science",
    "Mathematics",
    "Mechanical Engineering",
    "Microbiology",
    "Molecular Biology",
    "Neuroscience",
    "Nuclear Physics",
    "Oceanography",
    "Organic Chemistry",
    "Paleontology",
    "Pathology",
    "Pharmacology",
    "Physics",
    "Physiology",
    "Planetary Science",
    "Plant Science",
    "Quantum Physics",
    "Software Engineering",
    "Statistics",
    "Systems Biology",
    "Theoretical Physics",
    "Toxicology",
    "Virology",
    "Zoology",
    "Artificial Intelligence",
    "Machine Learning",
    "Network Science",
    "Cognitive Science",
    "Cybersecurity",
    "Developmental Biology",
    "Environmental Engineering",
    "Evolutionary Biology",
    "Forensic Science",
    "Genomics",
    "Hydrology",
    "Meteorology",
    "Microelectronics",
    "Nanotechnology",
    "Neuropsychology",
    "Optics",
    "Pharmaceutical Sciences",
    "Physical Chemistry",
    "Quantum Computing",
    "Renewable Energy",
    "Robotics",
    "Software Development",
    "Structural Biology",
    "Synthetic Biology",
    "Web Development",
    "Aerospace Engineering",
    "Agricultural Science",
    "Anatomy",
    "Animal Science",
    "Atmospheric Sciences",
    "Biomedical Engineering",
    "Cell Biology",
    "Cognitive Neuroscience",
    "Computational Chemistry",
    "Cryogenics",
    "Earth Science",
    "Electrical Engineering",
    "Entomology",
    "Genetic Engineering",
    "Geography",
    "Human-Computer Interaction",
    "Immunotherapy",
    "Industrial Engineering",
    "Information Theory",
    "Inorganic Chemistry",
    "Logic",
    "Mathematical Biology",
    "Mycology",
    "Operational Research",
    "Paleoecology",
    "Physical Oceanography",
    "Plant Pathology",
    "Psychophysics",
    "Public Health",
    "Quantum Mechanics",
    "Seismology",
    "Sociobiology",
    "Soil Science",
    "Space Science",
    "Spectroscopy",
    "Thermodynamics",
    "Vaccinology",
    "Veterinary Medicine",
    "Accountancy",
    "Anthropology",
    "Applied Mathematics",
    "Architecture",
    "Art",
    "Artificial Intelligence",
    "Bioengineering",
    "Biological Sciences",
    "Biotechnology",
    "Business Administration",
    "Chemical Engineering",
    "Chemistry",
    "Civil Engineering",
    "Classical Studies",
    "Cognitive Science",
    "Communication",
    "Computer Engineering",
    "Computer Science",
    "Criminal Justice",
    "Cybersecurity",
    "Data Analysis",
    "Dentistry",
    "Design",
    "Economics",
    "Education",
    "Electrical Engineering",
    "English Literature",
    "Environmental Science",
    "Epidemiology",
    "Ethics",
    "Film Production",
    "Finance",
    "Forensic Science",
    "Genetics",
    "Geography",
    "Geology",
    "Graphic Design",
    "History",
    "Hospitality Management",
    "Human Resources Management",
    "Immunology",
    "Industrial Design",
    "Information Systems",
    "Information Technology",
    "International Relations",
    "Journalism",
    "Law",
    "Linguistics",
    "Management",
    "Marketing",
    "Materials Science",
    "Mathematics",
    "Mechanical Engineering",
    "Media Studies",
    "Medicine",
    "Microbiology",
    "Music Performance",
    "Nursing",
    "Nutrition",
    "Occupational Therapy",
    "Pharmacology",
    "Philosophy",
    "Physics",
    "Political Science",
    "Psychology",
    "Public Health",
    "Public Policy",
    "Real Estate",
    "Religious Studies",
    "Robotics",
    "Social Work",
    "Sociology",
    "Software Development",
    "Statistics",
    "Theater",
    "Urban Planning",
    "Veterinary Medicine",
    "Visual Arts",
    "Web Development",
    "Zoology",
    "Meditation and stress reduction",
    "Cybersecurity trends and technologies",
    "Urban planning and sustainable cities",
    "Nutritional science and diet trends",
    "Comic books and graphic novels",
    "Architectural design and innovation",
    "Community service and volunteering",
    "Quantum computing and theoretical physics",
    "Theatre and performing arts",
    "DIY projects and crafting",
    "Marine biology and ocean exploration",
    "Renewable energy sources and technologies",
    "Social entrepreneurship and impact",
    "Digital marketing and advertising trends",
    "Public speaking and communication skills",
    "Geopolitical conflicts and resolutions",
    "Augmented reality and mixed reality",
    "Photography and visual storytelling",
    "Forensic science and criminal investigation",
    "Genealogy and family history research",
    "Agriculture and sustainable farming",
    "E-commerce trends and strategies",
    "Anthropology and human societies",
    "Wearable technology and smart devices",
    "Mental health advocacy and awareness",
    "Outdoor recreation and survival skills",
    "Crypto-currencies and blockchain technology",
    "Biotechnology and genetic engineering",
    "Aviation and aerospace",
    "Meteorology and weather prediction",
    "Public health policies and initiatives",
    "Folklore and mythology",
    "Legal justice and reform",
    "Urban legends and mysteries",
    "Pedagogy and teaching methods",
    "Wildlife conservation and biodiversity",
    "Nanotechnology and microfabrication",
    "Logistics and supply chain management",
    "Archaeology and ancient discoveries",
    "Workplace diversity and inclusion",
    "Time management and productivity",
    "Alternative medicine and holistic health",
    "Stand-up comedy and humor",
    "Pandemics and global health crises",
    "Philanthropy and charitable giving",
    "Esports and competitive gaming",
    "Myth busting and scientific skepticism",
    "Travel blogging and digital nomadism",
    "Feminism and gender studies",
    "Minimalism and simple living",
    "Underwater exploration and diving",
    "Volcanology and geological phenomena",
    "Experimental music and sound art",
    "Cyber-physical systems and IoT",
    "Urban farming and green roofs",
    "Magic and illusion",
    "Craft beer and brewing",
    "Museums and cultural institutions",
    "Puppetry and animation",
    "Indigenous cultures and traditions",
    "Acoustics and sound engineering",
    "Public art and murals",
    "Tiny houses and alternative living spaces",
    "Dark tourism and historical sites",
    "Aquaponics and hydroponics",
    "Non-verbal communication and body language",
    "Bird watching and ornithology",
    "Philatelic collecting and history",
    "Home automation and smart homes",
    "Kinesiology and human movement",
    "High-speed travel technologies",
    "Upcycling and creative reuse",
    "Stargazing and celestial events",
    "Gerontology and aging",
    "Retro gaming and game preservation",
    "Biohacking and self-optimization",
    "Desertification and land restoration",
    "Collective intelligence and crowdsourcing",
    "Astrophotography and cosmic visuals",
    "Permaculture and regenerative agriculture",
    "Silent retreats and mindfulness practices",
    "Dance styles and cultural expressions",
    "Tabletop gaming and role-playing games",
    "Bookbinding and paper arts",
    "Urban exploration and abandoned places",
    "Lo-fi music and aesthetic movements",
    "Digital nomadism and remote work trends",
    "Skateboarding culture and history",
    "Soap making and natural cosmetics",
    "Herbalism and plant-based remedies",
    "Biomimicry and nature-inspired design",
    "Sensory experiences and ASMR",
    "Sustainable fashion and ethical brands",
    "Robotics competitions and education",
    "Home brewing and distillation",
    "Space weather and cosmic phenomena",
    "Aerial photography and drone cinematography",
    "Time capsules and messages to the future",
    "Intermittent fasting and health effects",
    "Urban sketching and plein air painting",
    "Virtual choirs and collaborative music projects",
    "Shared economies and collaborative consumption",
    "Vintage electronics and technology restoration",
    "Language games and puzzles",
    "Parkour and free running",
    "Nuclear energy and safety debates",
    "Sleep science and dream analysis",
    "Composting and waste reduction",
    "Shipwrecks and underwater archaeology",
    "Circus arts and street performances",
    "Night photography and light painting",
    "Zero-waste lifestyle and practices",
    "Glaciology and ice formations",
    "Mushroom foraging and cultivation",
    "Bullet journaling and personal organization",
    "Space tourism and commercial spaceflight",
    "Cave exploration and speleology",
    "Kombucha brewing and fermentation sciences",
    "Privacy rights and data protection",
    "Sand sculpting and beach arts",
    "Live streaming culture and platforms",
    "Origami and paper crafts",
    "Survivalism and prepping",
    "Flash fiction and micro-storytelling",
    "Post-apocalyptic fiction and worldbuilding",
    "Stop motion animation and filmmaking",
    "Digital libraries and online archives",
    "Alternative energy vehicles and transportation",
    "Hydrotherapy and water-based healing",
    "Experimental theater and interactive performances",
    "Ocean conservation and marine protected areas",
    "Houseplants and indoor gardening",
    "Cognitive biases and decision-making",
    "Virtual reality filmmaking and storytelling",
    "Renaissance fairs and historical reenactment",
    "Drone racing and aerial competitions",
    "Choirs and vocal ensembles",
    "Mountain biking and trail adventures",
    "Smart cities and urban innovation",
    "Rock climbing and bouldering",
    "3D printing in medicine and healthcare",
    "Tutorial creation and online education",
    "Dark skies and light pollution awareness",
    "Aquariums and marine life sanctuaries",
    "Snow sports and winter adventures",
    "Recycling innovations and solutions",
    "Jazz history and improvisation",
    "Green architecture and eco-friendly construction",
    "Luxury travel and exclusive destinations",
    "Food styling and photography",
    "Underground music and indie labels",
    "Historical swordsmanship and martial arts",
    "Mixed martial arts and combat sports",
    "Voice acting and audio drama",
    "Cosplay and costume design",
    "Mindfulness in education and schools",
    "Fan fiction communities and creativity",
    "Flash mobs and public interventions",
    "Zero gravity and space simulations",
    "Kite flying and aerodynamics",
    "Carnivals and amusement parks",
    "Silicon Valley and tech entrepreneurship",
    "Antarctic expeditions and research stations",
    "Long-exposure photography and techniques",
    "Big data and analytics in sports",
    "Urban beekeeping and pollinator gardens",
    "Homesteading and self-sufficiency",
    "Social innovation and design thinking",
    "Ornamental gardening and landscape design",
    "Extreme weather chasing and photography",
    "Community choirs and social singing",
    "Crystal healing and metaphysical properties",
    "Light festivals and illumination art",
    "Scrapbooking and memory keeping",
    "Off-grid living and energy independence",
    "Traditional boat building and sailing crafts",
    "Laser cutting and engraving crafts",
    "Virtual tours and digital travel experiences",
    "Tattoo art and body modification",
    "Digital detox and unplugging",
    "Puzzle design and escape rooms",
    "Philosophy of mind and consciousness",
    "Recreational mathematics and number games",
    "Treehouses and elevated living spaces",
    "Biophilic design and nature integration",
    "Handwriting analysis and graphology",
    "Classical mythology and epic tales",
    "Basket weaving and fiber arts",
    "Net zero living and carbon footprint reduction",
    "Modernist cuisine and food science",
    "Paleontology and dinosaurs discoveries",
    "Tiny computing devices and nanocomputers",
    "Special effects makeup and prosthetics",
    "Historical linguistics and language evolution",
    "Stoicism and ancient philosophies in modern life",
    "Public libraries evolution and digital resources",
    "Craft cider making and apple varietals",
    "Ghost towns and abandoned places exploration",
    "Astronaut training and space missions preparation",
    "Bioethical issues in modern science",
    "Street art and urban interventions",
    "3D scanning and digital preservation of artifacts",
    "Immersive theater and sensory experiences",
    "Natural language processing and computational linguistics",
    "Citizen science projects and collaborative research",
    "Cognitive computing and human-computer interaction",
    "Molecular gastronomy and culinary innovation",
    "Postmodern architecture and design theory",
    "Electric aviation and sustainable air travel",
    "Windsurfing and water sports",
    "Sleep hacking and performance optimization",
    "Wildcrafting and ethical foraging",
    "Ethnomusicology and world music exploration",
    "Wearable art and fashion tech",
    "Retrofuturism and vintage visions of the future",
    "Analog photography and darkroom techniques",
    "Neotropical birds and biodiversity conservation",
    "E-safety and digital citizenship",
    "Smart textiles and materials innovation",
    "Folk medicine and traditional healing",
    "Underground literature and counterculture",
    "Dark matter and cosmic mysteries",
    "Aquatic ecosystems and coral reef conservation",
    "Time travel theories and temporal paradoxes",
    "Neuroplasticity and brain training",
    "Ultramarathon running and endurance sports",
    "Urban cycling and bike-friendly cities",
    "Crowdfunding for creative projects",
    "Adaptive sports and inclusive athletics",
    "Constructivist education and learning by doing",
    "Speculative fiction and future scenarios",
    "Silent films and early cinema history",
    "Harmony singing and vocal arrangements",
    "Grief counseling and bereavement support",
    "Brain-computer interfaces and neurotechnology",
    "Vertical farming and urban agriculture advancements",
    "Beekeeping and pollinator health",
    "Binaural beats and auditory illusions",
    "Upcoming space telescopes and cosmic observation",
    "Sustainable textiles and fashion recycling",
    "Cultural preservation and digitization projects",
    "Action sports and extreme activities",
    "Ethical hacking and cybersecurity defense",
    "Transhumanism and human augmentation",
    "Political satire and social commentary",
    "Industrial archaeology and heritage conservation",
    "Ergonomic design and workspace optimization",
    "Natural building and eco-construction techniques",
    "Community radio and independent broadcasting",
    "Board game design and tabletop innovation",
    "Microgreens cultivation and urban farming",
    "Ice sculpting and cold art forms",
    "Solar sailing and space propulsion",
    "Interpretive dance and movement expression",
    "Biofeedback and physiological monitoring",
    "Guerrilla gardening and green activism",
    "Subaquatic archaeology and sunken treasures",
    "Hyperloop and future mass transit systems",
    "Ecovillages and sustainable communities",
    "Smart grids and energy efficiency",
    "Paper engineering and pop-up book art",
    "Freerunning and urban acrobatics",
    "Parenting in the digital age",
    "Bioacoustics and soundscape ecology",
    "Choir conducting and musical leadership",
    "Dystopian literature and social critique",
    "Dynamic architecture and transforming spaces",
    "Quantified self and personal analytics",
    "Cross-cultural communication and bridging divides",
    "Supersonic travel and future aviation",
    "Living walls and vertical gardens",
    "Hard science fiction and technical accuracy",
    "Ethnobotany and plant wisdom",
    "Space habitats and living off-planet",
    "Oral history projects and storytelling preservation",
    "Holistic education and whole child approaches",
    "Aerial silk and circus arts",
    "DIY synthesizers and electronic music crafting",
    "Microadventures and local exploration",
    "Wilderness therapy and nature healing",
    "Telepresence and remote interaction technologies",
    "Functional foods and nutraceuticals",
    "Ethical consumerism and conscious buying",
    "Historical reenactment and living history",
    "Interactive documentaries and immersive journalism",
    "Klezmer music and cultural revival",
    "Ludology and the study of games",
    "Poi spinning and flow arts",
    "Interlocking and modular design",
    "Extreme metal music and subculture",
    "Mycology and the study of fungi",
    "Smart prosthetics and advances in bionics",
    "Renaissance music and historical instruments",
    "Slow food movement and gastronomic heritage",
    "Fan cultures and media fandom studies",
    "Modern ruins and the aesthetics of decay",
    "Ice climbing and vertical ice adventures",
    "Post-digital art and new media genres",
    "Living museums and experiential history",
    "Soundscape design and acoustic ecology",
    "Ephemeral art and temporary installations",
    "AI in creative arts and design exploration",
    "Canyoneering and slot canyon adventures",
    "Somaesthetics and body-mind practices",
    "Rural revitalization and small-town innovation",
    "Ancient board games and traditional play",
    "Viral evolution and pandemic forecasting",
    "Volunteering abroad and cultural exchange",
    "Nootropics and cognitive enhancers",
    "Kinetic sculpture and moving art",
    "Reclaimed spaces and adaptive reuse",
    "Perfumery and the art of scent creation",
    "Narrative medicine and storytelling in healthcare",
    "Planetary defense and asteroid monitoring",
    "Ice hotels and unique cold climate architecture",
    "Haptic technology and tactile feedback",
    "Psychedelic therapy and consciousness expansion",
    "Labyrinth walking and meditative paths",
    "Craft distilling and spirits innovation",
    "Tiny satellites and CubeSat missions",
    "Green chemistry and sustainable manufacturing",
    "Alternative schooling models and education reform",
    "Cryptology and secret communication",
    "Wilderness survival skills and bushcraft",
    "Steampunk culture and retrofuturistic design",
    "Urban mythology and contemporary legends",
    "Indie film making and grassroots cinema",
    "Particle physics and the hunt for new particles",
    "Material science breakthroughs and applications",
    "Shadow theater and silhouette animation",
    "Climate fiction (Cli-Fi) and environmental narratives",
    "Robot ethics and autonomous systems governance",
    "Mass spectrometry and molecular analysis",
    "Fingerprinting art and the science of provenance",
    "Capoeira and martial arts dance fusion",
    "Uncontacted peoples and remote tribes",
    "Voice synthesis and artificial vocal technologies",
    "Quantum consciousness theories and discussions",
    "Storytelling through data visualization",
    "Smart mirrors and interactive displays",
    "Metropolitan gardening and city green spaces",
    "Holotropic breathwork and altered states",
    "Deaf culture and sign language poetry",
    "Rapid prototyping and makerspaces",
    "Fossil hunting and paleoecology",
    "Bioart and biological media",
    "Aquathlon and multisport endurance competitions",
    "Laser harps and innovative musical instruments",
    "Guerilla filmmaking and independent productions",
    "Zero-energy buildings and passive house standards",
    "Vocaloid music and synthetic pop",
    "Cryptocurrency mining and blockchain ecosystems",
    "Longevity science and life extension",
    "Professional blogging and content creation",
    "Blacksmithing and metalwork artistry",
    "Recumbent biking and alternative cycling",
    "Sonic branding and audio identity",
    "Toy design and the psychology of play",
    "Esotericism and mystical philosophies",
    "Imaginary languages and conlangs",
    "Tactile interfaces and tangible computing",
    "Bushido and samurai culture",
    "Crowdsourced science and collaborative experiments",
    "Flash fiction and short-short stories",
    "Lost civilizations and speculative archaeology",
    "Nanomedicine and targeted drug delivery",
    "Buddhism in the modern world",
    "Modernist poetry and experimental literature",
    "Suborbital space flights and commercial astronauts",
    "Cognitive enhancement devices",
    "Underground comics and alternative graphic novels",
    "Ancient textiles and fabric history",
    "Skyspace art and immersive light environments",
    "Quantum art and physics-inspired creations",
    "Survival horror and psychological thrillers in gaming",
    "Architectural acoustics and soundscaping",
    "Magic realism and fantastical storytelling",
    "Vintage computers and retro technology",
    "Passenger drones and urban air mobility",
    "Low-impact development and green urban planning",
    "Fermented foods and probiotic diets",
    "Ecotherapy and the healing power of nature",
    "Food sovereignty and community agriculture",
    "Spectral music and microtonal compositions",
    "Artificial coral reefs and marine restoration",
    "Citizen diplomacy and grassroots peacebuilding",
    "Anti-gravity research and levitation experiments",
    "Microexpressions and facial emotion recognition",
    "Body painting and temporary art forms",
    "Exoplanetary discovery and characterization",
    "Aurora photography and night sky wonders",
    "Mindful eating and conscious consumption",
    "Underground dance and electronic music subcultures",
    "Sensory gardens and therapeutic landscapes",
    "Acapella music and vocal arrangements",
    "Adaptogens and stress-relieving herbs",
    "Experimental cinema and non-narrative films",
    "Landscape urbanism and ecological design",
    "Puzzle solving and competitive puzzling",
    "Experiential learning and outdoor education",
    "DIY robotics and home automation projects",
    "Sound healing and vibrational therapy",
    "Maglev trains and frictionless travel",
    "Perfume chemistry and scent science",
    "Aquascaping and underwater gardens",
    "Living history farms and agricultural museums",
    "Mathematical art and geometric design",
    "Nomadic lifestyle and long-term travel",
    "Typography and font design",
    "Sustainable jewelry and ethical gem sourcing",
    "Circular economy and waste-to-wealth systems",
    "Animal communication and interspecies relationships",
    "Seasteading and oceanic living",
    "Cloud seeding and weather modification",
    "Virtual choirs and mass online collaborations",
    "Algae biofuels and aquatic biomass",
    "Open-source hardware and community-driven technology",
    "Cabinet of curiosities and wunderkammers",
    "Ethnopharmacology and traditional medicines",
    "Global scavenger hunts and adventure challenges",
    "Eco-villages and intentional communities",
    "Adventure photography and expedition documenting",
    "Folk horror and rural Gothic stories",
    "Quantum encryption and secure communication",
    "Therapeutic landscapes and healing environments",
    "Rooftop gardens and green roofs",
    "Ephemera collecting and paper artifacts",
    "Yarn bombing and street knitting",
    "Microdosing and cognitive enhancement",
    "Illustrated journals and creative diaries",
    "Tactical urbanism and city hacking",
    "Speculative biology and imagined ecosystems",
    "Landscape architecture and outdoor space design",
    "Minimalist travel and ultralight backpacking",
    "Submersibles and deep-sea exploration",
    "Orchid cultivation and rare flowers",
    "Wildlife filmmaking and nature documentaries",
    "Infrared photography and unseen landscapes",
    "Sustainable tourism and responsible travel",
    "Cyborg art and human-machine collaborations",
    "Dark sky reserves and astrotourism",
    "Historical reenactments and time period immersion",
    "Superfoods and nutritional powerhouses",
    "Linguistic puzzles and cryptic languages",
    "DIY electronics and circuit bending",
    "Food forests and perennial agriculture",
    "Bioacoustic monitoring and ecosystem health",
    "Living sculptures and biological art",
    "Experimental archaeology and ancient technologies",
    "Ultralight aviation and personal flying devices",
    "Social impact games and meaningful play",
    "Outdoor education and environmental literacy",
    "Literary cafes and bookshop cultures",
    "Comparative mythology and universal themes",
    "Flying cars and vertical takeoff vehicles",
    "Minimalist architecture and design philosophy",
    "Psychoacoustics and the perception of sound",
    "Gastronomic tourism and culinary adventures",
    "Holistic veterinary medicine and animal wellness",
    "Precious metal clay (PMC) jewelry and art",
    "Found sound and field recording",
    "Ancient grains and heritage crops",
    "Digital humanities and technology in academia",
    "Indie bookstores and literary culture",
    "Flash mobs and spontaneous performances",
    "Lunar bases and moon colonization concepts",
    "Sound mapping and acoustic ecology studies",
    "Geoengineering and climate intervention",
    "Trashion and upcycled fashion",
    "Psychedelic art and visionary culture",
    "Lifelogging and digital self-tracking",
    "Renaissance festivals and historical fairs",
    "Origins of language and communication evolution",
    "Underwater music and aquatic concerts",
    "Pollinator pathways and bee boulevards",
    "Zero emission buildings and sustainable design",
    "Quantum mechanics and the nature of reality",
    "Digital detox retreats and unplugging experiences",
    "Cymatics and the visualization of sound",
    "Heritage crafts and traditional skills",
    "Bioinspired design and nature mimicry",
    "Ancient astronomy and celestial navigation",
    "Urban wildlife and coexisting with nature",
    "Sport kite flying and competitive team flying",
    "Unusual sports and quirky competitions",
    "Homemade instruments and alternative sound sources",
    "Community-supported agriculture (CSA) and local food",
    "Slow cinema and minimalist filmmaking",
    "Cloud art and atmospheric phenomena",
    "Street magic and urban illusion",
    "Digital anthropology and online cultures",
    "Modular synthesizers and electronic soundscapes",
    "Butterfly gardens and pollinator conservation",
    "Hacker spaces and maker communities",
    "Precarious architecture and balancing structures",
    "Flash animation and web cartoons",
    "Interstellar messages and cosmic communication",
    "Independent zines and DIY publishing",
    "Art cars and mobile masterpieces",
    "Paragliding and free-flight sports",
    "Vertical dance and aerial performances",
    "Underground libraries and secret archives",
    "Closed-loop systems and sustainable cycles",
    "Biochar and soil regeneration",
    "Urban spelunking and exploring hidden spaces",
    "Time-lapse photography and motion capture",
    "Metacognition and thinking about thinking",
    "Cave paintings and ancient art discoveries",
    "Gastropubs and the craft beer revolution",
    "Supercontinents and geological history",
    "Asteroid mining and space resources",
    "Artificial islands and floating cities",
    "Sound baths and meditative listening",
    "Ethical dilemmas in artificial intelligence",
    "Quantified ecology and environmental sensors",
    "Memory palaces and mnemonic techniques",
    "Whisper networks and grassroots information sharing",
    "Future cities and speculative urbanism",
    "Post-digital crafts and handmade technology",
    "Toy hacking and creative repurposing",
    "Binaural recording and immersive audio",
    "Eco-fiction and green narratives",
    "Interactive art and participatory installations",
    "Music psychology and the effects of sound",
    "Cosplay photography and costume showcases",
    "Perceptual art and sensory illusions",
    "Arctic expeditions and polar research",
    "Kitesurfing and wind-powered sports",
    "Living bridges and natural architecture",
    "Space junk and orbital debris cleanup",
    "Rhythmic gymnastics and expressive movement",
    "Solar punk and optimistic futures",
    "Underground cinema and cult films",
    "Sonic weapons and acoustic defense",
    "Theremin playing and electronic music history",
    "Narrative medicine and storytelling in health",
    "Breaking codes and cryptanalysis",
    "Anti-fashion and subversive style",
    "Historical fashion and costume recreation",
    "Lost arts and forgotten crafts",
    "Aquaponics and integrated agriculture",
    "Creative nonfiction and the art of storytelling",
    "Guerilla art and unexpected interventions",
    "Altered books and book sculpting",
    "Silent discos and wireless music festivals",
    "Container gardening and compact horticulture",
    "Superhero mythology and comic book analysis",
    "Wearable computing and smart garments",
    "Insect cuisine and entomophagy",
    "Ceramic arts and pottery techniques",
    "Sustainable aquaculture and fish farming",
    "Bioluminescence and living light sources",
    "Ice wine and extreme viticulture",
    "Augmented art and technology-enhanced creativity",
    "Architectural photography and building portraits",
    "Experimental food and avant-garde cuisine",
    "Historical espionage and codebreaking",
    "Urban forestry and city trees",
    "Drone cinematography and aerial filming",
    "Ecological art and environmental installations",
    "Popup books and mechanical paper engineering",
    "Deep learning and neural networks in art",
    "Parametric design and algorithmic architecture",
    "Unconventional materials and experimental fashion",
    "Slow TV and real-time broadcasting",
    "Conceptual art and idea-based creations",
    "Kinetic typography and animated text",
    "Recreational tree climbing and canopy exploration",
    "Polyphonic overtone singing and harmonic voices",
    "Bibliotherapy and the healing power of books",
    "Shared reading and community book clubs",
    "Aquatic plants and water gardening",
    "Vegan leather and sustainable materials",
    "Invisible art and conceptual pieces",
    "Urban legends and folklore research",
    "Home automation and connected devices",
    "Tea culture and ceremonial traditions",
    "Post-natural history and future ecologies",
    "Wild fermentation and traditional food preservation",
    "Geocaching and real-world treasure hunts",
    "House music and electronic dance culture",
    "Regenerative agriculture and farming for the future",
    "Whimsical architecture and playful spaces",
    "Aquaculture innovation and sustainable seafood",
    "Digital wellness and managing screen time",
    "Ethnographic film and documentary storytelling",
    "Space archeology and satellite imaging",
    "Pop-up architecture and temporary structures",
    "Book arts and creative publishing",
    "Artificial photosynthesis and energy solutions",
    "Narrative architecture and storytelling spaces",
    "Cyberpunk aesthetics and futuristic subcultures",
    "Cinema verite and realistic filmmaking",
    "Living statues and performance art",
    "Sand animation and kinetic art",
    "Independent radio and underground broadcasts",
    "Persuasive design and behavioral change",
    "Futurist cuisine and experimental dining",
    "Desert landscaping and xeriscaping",
]

more_instruct_themes = [
    "Global Cultures and Societies",
    "Modern and Ancient Civilizations",
    "Innovations in Science and Technology",
    "Environmental Conservation and Biodiversity",
    "World Religions and Philosophical Thought",
    "Global Economy and International Trade",
    "Public Health and Pandemic Response",
    "Human Rights and Social Justice Issues",
    "Political Systems and International Relations",
    "Major Historical Events and their Impact",
    "Advancements in Medicine and Healthcare",
    "Fundamentals of Physics and the Cosmos",
    "Cognitive Development and Learning Theories",
    "Sustainable Development and Green Technologies",
    "Media Literacy and News Analysis",
    "Classical and Modern Literature",
    "Fundamentals of Mathematics and Logic",
    "Social Psychology and Group Dynamics",
    "Emerging Trends in Education",
    "Civic Engagement and Community Organizing",
]

ABILITIES = [
    "synthesis",
    "evaluation",
    "prediction",
    "comparison",
    "abstraction",
    "induction",
    "logic",
    "recall",
    "critical thinking",
    "decision making",
    "analysis",
    "problem-solving",
    "creativity",
]

FORMATS = [
    "academic excersizes",
    "brainstorming monologue",
    "code",
    "tutorial",
    "guide",
    "creative writing",
    "critique",
    "dialogue",
    "instructions",
    "domain specific tasks",
    "email",
    "joke",
    "lecture",
    "letter",
    "long-form content",
    "quizz",
    "news piece",
    "oath",
    "poem",
    "research paper",
    "review",
    "roleplay",
    "satire",
    "script",
    "debate",
    "deliberations",
    "speech",
    "story",
    "technical report",
    "textbook",
]
