#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "click",
#   "requests",
# ]
# ///

import json
import sys
from typing import TypedDict

import click
import requests


# Duplicates of structs from the changelog generator script

class ChangeEntry(TypedDict):
    subject: str
    sha: str
    scopes: list[str]
    patch_id: str
    impacted_projects: list[str]
    type: str


class Changelog(TypedDict):
    new_ref: str
    previous_ref: str | None
    new_changes: dict[str, list[ChangeEntry]]
    dropped_changes: dict[str, list[ChangeEntry]]
    deduplicated_groups: list[list[ChangeEntry]]


def build_slack_blocks(changelog: Changelog, title: str, repository: str) -> list[dict]:
    """Build Slack Block Kit blocks from changelog data"""
    curr_ref = changelog["new_ref"]
    has_changes = any(changelog["new_changes"].values())
    has_dropped = any(changelog["dropped_changes"].values())
    deduplicated_groups = changelog.get("deduplicated_groups", [])

    blocks = [
        {"type": "header", "text": {"type": "plain_text", "text": title}},
    ]

    if has_changes:
        for category, changes in changelog["new_changes"].items():
            if not changes:
                continue

            lines = [f"*{category}*"]
            for change in changes:
                sha_short = change["sha"][:7]
                commit_url = f"https://github.com/{repository}/commit/{change['sha']}"

                if change.get("scopes"):
                    scopes_str = ", ".join(change["scopes"])
                    scope_prefix = f"*{scopes_str}*: "
                else:
                    scope_prefix = ""

                lines.append(f"• {scope_prefix}{change['subject']} (<{commit_url}|`{sha_short}`>)")

            blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": "\n".join(lines)}})

    if has_dropped:
        blocks.append({"type": "divider"})

        lines = ["*⚠️ Dropped commits*"]
        for category, changes in changelog["dropped_changes"].items():
            if not changes:
                continue
            lines.append(f"\n*{category}*")
            for change in changes:
                sha_short = change["sha"][:7]
                commit_url = f"https://github.com/{repository}/commit/{change['sha']}"

                if change.get("scopes"):
                    scopes_str = ", ".join(change["scopes"])
                    scope_prefix = f"*{scopes_str}*: "
                else:
                    scope_prefix = ""

                lines.append(f"• {scope_prefix}{change['subject']} (<{commit_url}|`{sha_short}`>)")

        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": "\n".join(lines)}})

    if not (has_changes or has_dropped):
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": "_No changes in this release_"}})

    if deduplicated_groups:
        blocks.append(
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"\n({len(deduplicated_groups)} matching commits already present on `{curr_ref}`)",
                },
            }
        )

    return blocks


@click.command()
@click.option("--title", required=True, help="Title/header for the Slack message")
@click.option("--repository", envvar="GITHUB_REPOSITORY", required=True, help="GitHub repository (owner/repo)")
@click.option("--webhook-url", required=True, help="Slack webhook URL")
@click.option("--dry/--no-dry", default=False, help="Dry run: print payload instead of posting")
def main(title: str, repository: str, webhook_url: str, dry: bool) -> None:
    """
    Publish changelog to Slack
    Accepts changelog JSON object generated by the changelog action via stdin
    """
    changelog: Changelog = json.load(sys.stdin)
    payload = {"blocks": build_slack_blocks(changelog, title, repository)}

    if dry:
        click.echo(f"DRY RUN - Would POST to {webhook_url}:", err=True)
        click.echo(json.dumps(payload, indent=2))
        return

    try:
        click.echo(f"Posting changelog to Slack...", err=True)
        response = requests.post(webhook_url, json=payload, timeout=10)
        response.raise_for_status()
        click.echo(f"Successfully posted to Slack (status: {response.status_code})", err=True)
    except requests.exceptions.RequestException as e:
        click.echo(f"Failed to post to Slack: {e}", err=True)
        sys.exit(1)


if __name__ == "__main__":
    main()
