# Generated by Django 4.2.10 on 2024-04-12 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("miner", "0003_validator_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidatorBlacklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "validator",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="miner.validator",
                    ),
                ),
            ],
        ),
    ]
