# Generated by Django 4.2.10 on 2024-02-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("miner", "0003_validator_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="acceptedjob",
            name="output_upload_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="acceptedjob",
            name="output_upload_status_reported_to_validator",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="acceptedjob",
            name="output_upload_success",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
