# Generated by Django 4.2.13 on 2024-07-01 16:42

import compute_horde.executor_class
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("miner", "0006_remove_jobreceipt_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobreceipt",
            name="executor_class",
            field=models.CharField(
                default=compute_horde.executor_class.ExecutorClass["spin_up_4min__gpu_24gb"],
                max_length=255,
            ),
        ),
    ]
