# Generated by Django 4.2.13 on 2024-07-09 18:26

import compute_horde_core.executor_class
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("miner", "0007_validator_debug"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobStartedReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("validator_signature", models.CharField(max_length=256)),
                ("miner_signature", models.CharField(max_length=256)),
                ("job_uuid", models.UUIDField()),
                ("miner_hotkey", models.CharField(max_length=256)),
                ("validator_hotkey", models.CharField(max_length=256)),
                (
                    "executor_class",
                    models.CharField(
                        default=compute_horde_core.executor_class.ExecutorClass[
                            "spin_up_4min__gpu_24gb"
                        ],
                        max_length=255,
                    ),
                ),
                ("time_accepted", models.DateTimeField()),
                ("max_timeout", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameModel(
            old_name="JobReceipt",
            new_name="JobFinishedReceipt",
        ),
    ]
