# Generated by Django 4.2.16 on 2024-10-10 11:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("miner", "0008_jobstartedreceipt_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JobFinishedReceipt",
        ),
        migrations.DeleteModel(
            name="JobStartedReceipt",
        ),
    ]
