# Generated by Django 4.2.16 on 2024-11-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("miner", "0009_delete_jobfinishedreceipt_delete_jobstartedreceipt"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterMiner",
            fields=[
                ("hotkey", models.CharField(max_length=48, primary_key=True, serialize=False)),
                ("block", models.BigIntegerField(null=True)),
            ],
        ),
    ]
