# Generated by Django 4.2.16 on 2025-01-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("miner", "0010_clusterminer"),
    ]

    operations = [
        migrations.AddField(
            model_name="acceptedjob",
            name="executor_address",
            field=models.TextField(null=True),
        ),
    ]
