# Generated by Django 4.2.16 on 2025-02-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("miner", "0011_acceptedjob_executor_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acceptedjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING_FOR_EXECUTOR", "Waiting For Executor"),
                    ("WAITING_FOR_PAYLOAD", "Waiting For Payload"),
                    ("RUNNING", "Running"),
                    ("FINISHED", "Finished"),
                    ("FAILED", "Failed"),
                    ("REJECTED", "Rejected"),
                ],
                max_length=255,
            ),
        ),
    ]
