# Generated by Django 4.2.16 on 2025-02-07 13:52

from django.db import migrations, models

import compute_horde_miner.miner.models


class Migration(migrations.Migration):
    dependencies = [
        ("miner", "0011_acceptedjob_executor_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="acceptedjob",
            name="artifacts",
            field=models.JSONField(encoder=compute_horde_miner.miner.models.EnumEncoder, null=True),
        ),
    ]
