# Generated by Django 4.2.16 on 2025-02-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("miner", "0013_alter_acceptedjob_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="acceptedjob",
            name="error_detail",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="acceptedjob",
            name="error_type",
            field=models.TextField(default=None, null=True),
        ),
    ]
