# Generated by Django 4.2.11 on 2024-03-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="args",
            field=models.TextField(blank=True, help_text="arguments passed to the script or docker image"),
        ),
    ]
