# Generated by Django 4.2.11 on 2024-03-27 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_job_args"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="last_heartbeat",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
