# Generated by Django 4.2.11 on 2024-04-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_job_output_download_url_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="input_url",
            field=models.URLField(blank=True, help_text="URL to the input data source", max_length=1000),
        ),
    ]
