# Generated by Django 4.2.11 on 2024-04-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_job_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="validator",
            name="runner_version",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="validator",
            name="version",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
