# Generated by Django 4.2.11 on 2024-04-26 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_gpu_gpucount_hardwarestate_subnet_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinerVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(blank=True, default="", max_length=255)),
                (
                    "runner_version",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "miner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.miner",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["created_at"], name="core_minerv_created_4bf732_idx")],
            },
        ),
    ]
