# Generated by Django 4.2.11 on 2024-05-14 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_rename_clock_gpu_core_clock_remove_gpu_tflops_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="gpu",
            name="unique_gpu",
        ),
        migrations.RemoveIndex(
            model_name="gpu",
            name="idx_gpu_name",
        ),
        migrations.AlterField(
            model_name="gpu",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="minergpuspecs",
            name="gpu",
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to="core.gpu"),
        ),
        migrations.AlterField(
            model_name="minerspecs",
            name="total_hdd",
            field=models.PositiveIntegerField(blank=True, default=0, help_text="in kiB", null=True),
        ),
        migrations.AlterField(
            model_name="minerspecs",
            name="total_ram",
            field=models.PositiveIntegerField(blank=True, default=0, help_text="in kiB", null=True),
        ),
    ]
