# Generated by Django 4.2.11 on 2024-05-20 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0012_remove_gpu_unique_gpu_remove_gpu_idx_gpu_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "miners",
                    models.ManyToManyField(blank=True, related_name="preferred_by_users", to="core.miner"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="preferred_by_users",
                        to="core.validator",
                    ),
                ),
            ],
        ),
    ]
