# Generated by Django 4.2.11 on 2024-05-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_userpreferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_uuid", models.UUIDField()),
                ("miner_hotkey", models.CharField(max_length=256)),
                ("validator_hotkey", models.CharField(max_length=256)),
                ("time_started", models.DateTimeField()),
                ("time_took_us", models.BigIntegerField()),
                ("score_str", models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="miners",
            field=models.ManyToManyField(
                blank=True,
                help_text="miners which will be prioritized for this user; if none of them are present,                    other miners will be used",
                related_name="preferred_by_users",
                to="core.miner",
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="validators",
            field=models.ManyToManyField(
                blank=True,
                help_text="validators which will be prioritized for this user; if none of them are present,                    other validators will be used",
                related_name="preferred_by_users",
                to="core.validator",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobreceipt",
            constraint=models.UniqueConstraint(fields=("job_uuid",), name="unique_job_receipt_job_uuid"),
        ),
    ]
