# Generated by Django 4.2.11 on 2024-05-23 15:02

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_jobreceipt_alter_userpreferences_miners_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CpuSpecs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpu_model", models.CharField(default="", max_length=255)),
                ("cpu_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ExecutorSpecsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_id",
                    models.UUIDField(blank=True, default=None, help_text="job batch id", null=True),
                ),
                (
                    "measured_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GpuSpecs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gpu_count", models.PositiveIntegerField(default=0)),
                ("capacity", models.PositiveIntegerField(default=0, help_text="in MB")),
                (
                    "cuda",
                    models.CharField(default="", help_text="version", max_length=255),
                ),
                (
                    "driver",
                    models.CharField(default="", help_text="version", max_length=255),
                ),
                (
                    "graphics_speed",
                    models.PositiveIntegerField(default=0, help_text="in MHz"),
                ),
                (
                    "memory_speed",
                    models.PositiveIntegerField(default=0, help_text="in MHz"),
                ),
                ("power_limit", models.FloatField(default=0, help_text="in MHz")),
            ],
        ),
        migrations.CreateModel(
            name="OtherSpecs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("os", models.CharField(default="", max_length=255)),
                ("virtualization", models.CharField(default="", max_length=255)),
                (
                    "total_ram",
                    models.PositiveIntegerField(blank=True, default=0, help_text="in GB", null=True),
                ),
                (
                    "total_hdd",
                    models.PositiveIntegerField(blank=True, default=0, help_text="in GB", null=True),
                ),
                ("asn", models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RawSpecsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name="minerspecs",
            name="miner",
        ),
        migrations.RemoveField(
            model_name="minerspecs",
            name="validator",
        ),
        migrations.AlterField(
            model_name="gpu",
            name="capacity",
            field=models.PositiveIntegerField(default=0, help_text="in GB"),
        ),
        migrations.CreateModel(
            name="ParsedSpecsData",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="core.rawspecsdata",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MinerGpuSpecs",
        ),
        migrations.DeleteModel(
            name="MinerSpecs",
        ),
        migrations.AddIndex(
            model_name="rawspecsdata",
            index=django.contrib.postgres.indexes.HashIndex(fields=["data"], name="core_rawspe_data_e05b87_hash"),
        ),
        migrations.AddField(
            model_name="gpuspecs",
            name="gpu_model",
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to="core.gpu"),
        ),
        migrations.AddField(
            model_name="executorspecssnapshot",
            name="miner",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.miner"),
        ),
        migrations.AddField(
            model_name="executorspecssnapshot",
            name="raw_specs",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="raw_specs_data",
                to="core.rawspecsdata",
            ),
        ),
        migrations.AddField(
            model_name="executorspecssnapshot",
            name="validator",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.validator"),
        ),
        migrations.AddField(
            model_name="parsedspecsdata",
            name="cpu_specs",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cpu_specs",
                to="core.cpuspecs",
            ),
        ),
        migrations.AddField(
            model_name="parsedspecsdata",
            name="other_specs",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="other_specs",
                to="core.otherspecs",
            ),
        ),
        migrations.AddField(
            model_name="gpuspecs",
            name="parsed_specs",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specs",
                to="core.parsedspecsdata",
            ),
        ),
    ]
