# Generated by Django 4.2.11 on 2024-05-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_cpuspecs_executorspecssnapshot_gpuspecs_otherspecs_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="rawspecsdata",
            name="core_rawspe_data_e05b87_hash",
        ),
        migrations.AddIndex(
            model_name="rawspecsdata",
            index=models.Index(fields=["data"], name="idx_raw_spec_data"),
        ),
        migrations.AddConstraint(
            model_name="cpuspecs",
            constraint=models.UniqueConstraint(fields=("cpu_model", "cpu_count"), name="unique_cpu_specs"),
        ),
        migrations.AddConstraint(
            model_name="gpuspecs",
            constraint=models.UniqueConstraint(
                fields=(
                    "parsed_specs",
                    "gpu_model",
                    "gpu_count",
                    "capacity",
                    "cuda",
                    "driver",
                    "graphics_speed",
                    "memory_speed",
                    "power_limit",
                ),
                name="unique_gpu_specs",
            ),
        ),
        migrations.AddConstraint(
            model_name="otherspecs",
            constraint=models.UniqueConstraint(
                fields=("os", "virtualization", "total_ram", "total_hdd", "asn"),
                name="unique_other_specs",
            ),
        ),
        migrations.AddConstraint(
            model_name="rawspecsdata",
            constraint=models.UniqueConstraint(fields=("data",), name="unique_raw_specs_data"),
        ),
    ]
