# Generated by Django 4.2.11 on 2024-04-03 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0017_alter_otherspecs_os_alter_otherspecs_virtualization",
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
CREATE MATERIALIZED VIEW specs AS
  SELECT
    snapshot.measured_at,
    miner.ss58_address as miner_hotkey,
    snapshot.batch_id,
    other_specs.os,
    other_specs.virtualization,
    other_specs.total_hdd,
    other_specs.total_ram,
    cpu_specs.cpu_count,
    cpu_specs.cpu_model,
    gpu_specs.gpu_model_id as gpu_id,
    gpu_specs.capacity as vram,
    gpu_specs.cuda,
    gpu_specs.driver,
    gpu_specs.gpu_count,
    gpu_specs.graphics_speed,
    gpu_specs.memory_speed,
    gpu_specs.power_limit
  FROM
    core_executorspecssnapshot snapshot
    inner join core_parsedspecsdata specs on specs.id_id = snapshot.raw_specs_id
    inner join core_validator validator on validator.id = snapshot.validator_id
    inner join core_miner miner on miner.id = snapshot.miner_id
    right join core_gpuspecs gpu_specs on gpu_specs.parsed_specs_id = specs.id_id
    inner join core_cpuspecs cpu_specs on specs.cpu_specs_id = cpu_specs.id
    inner join core_otherspecs other_specs on specs.other_specs_id = other_specs.id
  where
    snapshot.measured_at > CURRENT_DATE - INTERVAL '3 months'
    and validator.ss58_address = '5F4tQyWrhfGVcNhoqeiNsR6KjD4wMZ2kfhLj4oHYuyHbZAc3'; -- OTF

  CREATE INDEX specs_miner_idx ON specs (miner_hotkey, batch_id, measured_at);
  CREATE INDEX specs_measured_at_idx ON specs (measured_at);
  """,
            reverse_sql="""
            DROP INDEX specs_miner_idx;
            DROP INDEX specs_measured_at_idx;
            DROP MATERIALIZED VIEW specs;
            """,
        ),
    ]
