# Generated by Django 4.2.13 on 2024-06-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_modify_specs_materialized_views"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="gpuspecs",
            name="unique_gpu_specs",
        ),
        migrations.AddField(
            model_name="gpuspecs",
            name="serial",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="gpuspecs",
            name="uuid",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="gpuspecs",
            constraint=models.UniqueConstraint(
                fields=(
                    "parsed_specs",
                    "gpu_model",
                    "gpu_count",
                    "capacity",
                    "cuda",
                    "driver",
                    "graphics_speed",
                    "memory_speed",
                    "power_limit",
                    "uuid",
                    "serial",
                ),
                name="unique_gpu_specs",
            ),
        ),
    ]
