# Generated by Django 4.2.13 on 2024-06-21 12:02

import typing

import compute_horde_core.output_upload
import compute_horde_core.volume
import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_job_executor_class_jobreceipt_executor_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="uploads",
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True,
                config=None,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                schema=django_pydantic_field.compat.django.GenericContainer(
                    list,
                    (
                        django_pydantic_field.compat.django.GenericContainer(
                            typing.Annotated,
                            (
                                compute_horde_core.output_upload.SingleFilePostUpload
                                | compute_horde_core.output_upload.SingleFilePutUpload,
                                django_pydantic_field.compat.django.FieldInfoContainer(
                                    None, (), {"discriminator": "output_upload_type"}
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="volumes",
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True,
                config=None,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                schema=django_pydantic_field.compat.django.GenericContainer(
                    list,
                    (
                        django_pydantic_field.compat.django.GenericContainer(
                            typing.Annotated,
                            (
                                compute_horde_core.volume.ZipUrlVolume | compute_horde_core.volume.SingleFileVolume,
                                django_pydantic_field.compat.django.FieldInfoContainer(
                                    None, (), {"discriminator": "volume_type"}
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ]
