# Generated by Django 4.2.13 on 2024-07-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_rename_jobreceipt_jobfinishedreceipt"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="jobfinishedreceipt",
            name="unique_job_receipt_job_uuid",
        ),
        migrations.AddConstraint(
            model_name="jobfinishedreceipt",
            constraint=models.UniqueConstraint(fields=("job_uuid",), name="unique_jobfinishedreceipt_job_uuid"),
        ),
    ]
