# Generated by Django 4.2.13 on 2024-07-09 18:56

import compute_horde.executor_class
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_remove_jobfinishedreceipt_unique_job_receipt_job_uuid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobStartedReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("job_uuid", models.UUIDField()),
                ("miner_hotkey", models.CharField(max_length=256)),
                ("validator_hotkey", models.CharField(max_length=256)),
                (
                    "executor_class",
                    models.CharField(
                        default=compute_horde.executor_class.ExecutorClass["spin_up_4min__gpu_24gb"], max_length=255
                    ),
                ),
                ("time_accepted", models.DateTimeField()),
                ("max_timeout", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="jobfinishedreceipt",
            name="executor_class",
        ),
        migrations.AddConstraint(
            model_name="jobstartedreceipt",
            constraint=models.UniqueConstraint(fields=("job_uuid",), name="unique_jobstartedreceipt_job_uuid"),
        ),
    ]
