# Generated by Django 4.2.15 on 2024-10-15 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_jobfinishedreceipt_job_uuid_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JobFinishedReceipt",
        ),
        migrations.DeleteModel(
            name="JobStartedReceipt",
        ),
    ]
