# Generated by Django 4.2.15 on 2024-10-24 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_delete_jobfinishedreceipt_delete_jobstartedreceipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="signature_info",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="core.signatureinfo",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="target_validator_hotkey",
            field=models.TextField(blank=True, default=None, help_text="target validator", null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="miner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="jobs", to="core.miner"
            ),
        ),
    ]
