# Generated by Django 4.2.16 on 2024-10-25 02:12

import typing

import compute_horde_core.volume
import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_job_signature_info_job_target_validator_hotkey_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="hf_repo_id",
            field=models.CharField(blank=True, default="", help_text="Huggingface model repo id", max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="hf_revision",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Huggingface model revision id: branch name / tag / commit hash",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="volumes",
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True,
                config=None,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                schema=django_pydantic_field.compat.django.GenericContainer(
                    list,
                    (
                        django_pydantic_field.compat.django.GenericContainer(
                            typing.Annotated,
                            (
                                compute_horde_core.volume.ZipUrlVolume
                                | compute_horde_core.volume.SingleFileVolume
                                | compute_horde_core.volume.HuggingfaceVolume,
                                django_pydantic_field.compat.django.FieldInfoContainer(
                                    None, (), {"discriminator": "volume_type"}
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ]
