# Generated by Django 4.2.16 on 2024-11-07 21:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_job_hf_repo_id_job_hf_revision_alter_job_volumes"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpu",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="rawspecsdata",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="signatureinfo",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="executorspecssnapshot",
            name="raw_specs",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="raw_specs_data", to="core.rawspecsdata"
            ),
        ),
        migrations.AlterField(
            model_name="parsedspecsdata",
            name="id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to="core.rawspecsdata"
            ),
        ),
    ]
