# Generated by Django 4.2.16 on 2024-11-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_gpu_created_at_rawspecsdata_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="signature",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
