# Generated by Django 4.2.18 on 2025-02-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_jobfeedback_signature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="artifacts",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="job",
            name="artifacts_dir",
            field=models.CharField(blank=True, help_text="image mount directory for artifacts", max_length=255),
        ),
    ]
