# Generated by Django 4.2.18 on 2025-02-14 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0035_job_artifacts_job_artifacts_dir"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="hotkey",
            field=models.CharField(
                blank=True,
                help_text="hotkey of job sender if hotkey authentication was used",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["hotkey"], name="idx_job_hotkey"),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("user__isnull", True), models.Q(("hotkey", ""), _negated=True)),
                    models.Q(("user__isnull", False), ("hotkey", "")),
                    _connector="OR",
                ),
                name="user_or_hotkey",
            ),
        ),
    ]
