# Generated by Django 4.2.19 on 2025-02-20 16:16

import typing

import compute_horde_core.volume
import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_job_hotkey_alter_job_user_job_idx_job_hotkey_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="volumes",
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True,
                config=None,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                schema=django_pydantic_field.compat.django.GenericContainer(
                    list,
                    (
                        django_pydantic_field.compat.django.GenericContainer(
                            typing.Annotated,
                            (
                                compute_horde_core.volume.InlineVolume
                                | compute_horde_core.volume.ZipUrlVolume
                                | compute_horde_core.volume.SingleFileVolume
                                | compute_horde_core.volume.HuggingfaceVolume,
                                django_pydantic_field.compat.django.FieldInfoContainer(
                                    None, (), {"discriminator": "volume_type", "evaluated": False}
                                ),
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ]
