# Generated by Django 4.2.17 on 2025-02-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_alter_job_volumes"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="cheated",
            field=models.BooleanField(default=False),
        ),
    ]
