# Generated by Django 4.2.19 on 2025-02-26 05:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_alter_job_args"),
        ("core", "0038_job_cheated"),
    ]

    operations = []
