# Generated by Django 4.2.19 on 2025-02-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_merge_0038_alter_job_args_0038_job_cheated"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="on_trusted_miner",
            field=models.BooleanField(default=False),
        ),
    ]
