# Generated by Django 4.2.19 on 2025-03-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_job_on_trusted_miner"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotkeyWhitelist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ss58_address", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
