# Generated by Django 4.2.19 on 2025-03-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_job_on_trusted_miner'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='streaming_client_cert',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='streaming_server_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='streaming_server_cert',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='streaming_server_port',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
