# Generated by Django 4.2.19 on 2025-03-27 23:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_job_on_trusted_miner"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="job",
            name="docker_image_or_raw_script",
        ),
        migrations.RemoveField(
            model_name="job",
            name="raw_script",
        ),
    ]
