# Generated by Django 4.2.19 on 2025-03-29 01:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_remove_job_docker_image_or_raw_script_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="input_url",
        ),
    ]
