# Generated by Django 4.2.19 on 2025-04-09 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_hotkeywhitelist"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="job",
            name="docker_image_or_raw_script",
        ),
        migrations.RemoveField(
            model_name="job",
            name="raw_script",
        ),
    ]
