# Generated by Django 4.2.19 on 2025-03-29 01:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_remove_job_input_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="hf_repo_id",
        ),
        migrations.RemoveField(
            model_name="job",
            name="hf_revision",
        ),
    ]
