# Generated by Django 4.2.19 on 2025-03-29 01:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_remove_job_hf_repo_id_remove_job_hf_revision"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="output_download_url",
        ),
        migrations.RemoveField(
            model_name="job",
            name="output_download_url_expires_at",
        ),
        migrations.RemoveField(
            model_name="job",
            name="output_upload_url",
        ),
    ]
