# Generated by Django 4.2.19 on 2025-04-09 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_remove_job_output_download_url_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserPreferences",
        ),
    ]
