# Generated by Django 4.2.19 on 2025-04-09 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_delete_userpreferences"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="signature_info",
        ),
        migrations.RemoveField(
            model_name="jobfeedback",
            name="signature_info",
        ),
        migrations.DeleteModel(
            name="SignatureInfo",
        ),
    ]
