# Generated by Django 4.2.19 on 2025-04-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_remove_job_signature_info_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="miner",
        ),
        migrations.AlterField(
            model_name="job",
            name="signature",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="target_validator_hotkey",
            field=models.TextField(default="", help_text="target validator"),
            preserve_default=False,
        ),
    ]
