# Generated by Django 4.2.19 on 2025-04-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_remove_job_signature_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="download_time_limit",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="execution_time_limit",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="upload_time_limit",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobstatus",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (-2, "Failed"),
                    (-1, "Rejected"),
                    (0, "Sent"),
                    (1, "Received"),
                    (2, "Accepted"),
                    (3, "Executor Ready"),
                    (4, "Volumes Ready"),
                    (5, "Execution Done"),
                    (6, "Completed"),
                ]
            ),
        ),
    ]
