# Generated by Django 4.2.19 on 2025-05-08 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_job_download_time_limit_job_execution_time_limit_and_more"),
        ("core", "0048_remove_job_miner_alter_job_signature_and_more"),
    ]

    operations = []
