# Generated by Django 4.2.19 on 2025-05-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_job_upload_results"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="streaming_client_cert",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="job",
            name="streaming_server_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="job",
            name="streaming_server_cert",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="job",
            name="streaming_server_port",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="jobstatus",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (-2, "Failed"),
                    (-1, "Rejected"),
                    (0, "Sent"),
                    (1, "Accepted"),
                    (2, "Completed"),
                    (3, "Streaming Ready"),
                ]
            ),
        ),
    ]
