# Generated by Django 4.2.19 on 2025-05-15 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_job_upload_results"),
        ("core", "0049_merge_20250508_1852"),
    ]

    operations = []
