# Generated by Django 4.2.19 on 2025-05-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_merge_20250515_1635"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="streaming_client_cert",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="job",
            name="streaming_server_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="job",
            name="streaming_server_cert",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="job",
            name="streaming_server_port",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="jobstatus",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (-2, "Failed"),
                    (-1, "Rejected"),
                    (0, "Sent"),
                    (1, "Received"),
                    (2, "Accepted"),
                    (3, "Executor Ready"),
                    (4, "Volumes Ready"),
                    (5, "Execution Done"),
                    (6, "Completed"),
                    (7, "Streaming Ready"),
                ]
            ),
        ),
    ]
