# Generated by Django 4.2.19 on 2025-08-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_job_streaming_client_cert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("unknown", "unknown"),
                    ("sent", "sent"),
                    ("received", "received"),
                    ("accepted", "accepted"),
                    ("executor_ready", "executor_ready"),
                    ("streaming_ready", "streaming_ready"),
                    ("volumes_ready", "volumes_ready"),
                    ("execution_done", "execution_done"),
                    ("completed", "completed"),
                    ("rejected", "rejected"),
                    ("failed", "failed"),
                    ("horde_failed", "horde_failed"),
                ]
            ),
        ),
    ]
