# Generated by Django 4.2.19 on 2025-08-12 09:05

from django.db import migrations, models


def forwards(apps, schema_editor):
    JobStatus = apps.get_model("core", "JobStatus")
    mapping = {
        -2: "failed",
        -1: "rejected",
        0: "sent",
        1: "received",
        2: "accepted",
        3: "executor_ready",
        4: "volumes_ready",
        5: "execution_done",
        6: "completed",
        7: "streaming_ready",
    }

    for old, new in mapping.items():
        JobStatus.objects.filter(status=old).update(status=new)


def backwards(apps, schema_editor):
    JobStatus = apps.get_model("core", "JobStatus")
    reverse_mapping = {
        "failed": -2,
        "rejected": -1,
        "sent": 0,
        "received": 1,
        "accepted": 2,
        "executor_ready": 3,
        "volumes_ready": 4,
        "execution_done": 5,
        "completed": 6,
        "streaming_ready": 7,
        "unknown": -2,
        "horde_failed": -2
    }
    for new, old in reverse_mapping.items():
        JobStatus.objects.filter(status=new).update(status=old)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_job_streaming_client_cert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("unknown", "unknown"),
                    ("sent", "sent"),
                    ("received", "received"),
                    ("accepted", "accepted"),
                    ("executor_ready", "executor_ready"),
                    ("streaming_ready", "streaming_ready"),
                    ("volumes_ready", "volumes_ready"),
                    ("execution_done", "execution_done"),
                    ("completed", "completed"),
                    ("rejected", "rejected"),
                    ("failed", "failed"),
                    ("horde_failed", "horde_failed"),
                ]
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
