# Generated by Django 4.2.19 on 2025-09-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_alter_jobstatus_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_namespace",
            field=models.CharField(
                blank=True, help_text="namespace specifying where the job comes from", max_length=100, null=True
            ),
        ),
    ]
