# Generated by Django 4.2.19 on 2025-07-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_jobstatus_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "sent"),
                    ("received", "received"),
                    ("accepted", "accepted"),
                    ("executor_ready", "executor_ready"),
                    ("streaming_ready", "streaming_ready"),
                    ("volumes_ready", "volumes_ready"),
                    ("execution_done", "execution_done"),
                    ("completed", "completed"),
                    ("rejected", "rejected"),
                    ("failed", "failed"),
                ]
            ),
        ),
        migrations.RunSQL(
            """
            UPDATE core_jobstatus SET status = CASE
                WHEN status = '-2' THEN 'failed'
                WHEN status = '-1' THEN 'rejected'
                WHEN status = '0' THEN 'sent'
                WHEN status = '1' THEN 'received'
                WHEN status = '2' THEN 'accepted'
                WHEN status = '3' THEN 'executor_ready'
                WHEN status = '4' THEN 'volumes_ready'
                WHEN status = '5' THEN 'execution_done'
                WHEN status = '6' THEN 'completed'
                WHEN status = '7' THEN 'streaming_ready'
                ELSE status
            END;
            """
        ),
    ]
