# Generated by Django on 2025-09-25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_job_job_namespace"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="cheated_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="job",
            name="cheated_message",
            field=models.TextField(default="unknown", blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="cheated_details",
            field=models.JSONField(default=dict, blank=True),
        ),
    ]
