# Generated by Django 4.2.19 on 2025-11-24 11:27

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_cheatedjobreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="jobstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("unknown", "unknown"),
                    ("pending", "pending"),
                    ("sent", "sent"),
                    ("received", "received"),
                    ("accepted", "accepted"),
                    ("executor_ready", "executor_ready"),
                    ("streaming_ready", "streaming_ready"),
                    ("volumes_ready", "volumes_ready"),
                    ("execution_done", "execution_done"),
                    ("completed", "completed"),
                    ("rejected", "rejected"),
                    ("failed", "failed"),
                    ("horde_failed", "horde_failed"),
                ]
            ),
        ),
    ]
